### ISSUE TITLE
Market reactions to move.

### ISSUE THREAD

**Issue by AdminHole** [Mantaro/MantaroBot#101]
I have noticed that It sometimes gets stuck on the 3rd page it happens a lot And I am wondering if there's a way to fix it.

**Comment by Kodehawa** [comment]
It times out in 45 seconds.

**Comment by MrLar** [comment]
*after

**Comment by Kodehawa** [comment]
lars plz

**Comment by AdminHole** [comment]
Oh thank you!

**Comment by MrLar** [comment]
You should make it longer tho @Kodehawa considering theres alot of pages and people might wanna look through it
