### ISSUE TITLE
Allowing Commands

### ISSUE THREAD

**Issue by Kuro1123** [Mantaro/MantaroBot#103]
Hey, I'm a mod in a server and for some reason we cant seem to allow the moderation functions to the mods, only the admin. How do we fix this issue?

**Comment by mina9999** [comment]
give them the bot commander role
koda is lazy to reply

**Comment by MrLar** [comment]
Commands are locked to permissions for instance ban requires them to have Ban Members. Pretty self explanatory. For commands like opts you can give them a role called Bot Commander and they'll be able to.
