### ISSUE TITLE
Bug Fix: Marriage proposal ends games

### ISSUE THREAD

**Issue by cgodon** [Mantaro/MantaroBot#110]
If someone is in a game, and another player does a marriage propsoal, the game ends for the player

EX)
Person A: ~>game pokemon
(game starts)
Person B: ~>marry @Person C
(marriage message pops and game ends for player A)
![botbug](https://user-images.githubusercontent.com/1876831/35348685-c128ddba-0106-11e8-967b-4eed4f9d9066.png)

**Comment by MrLar** [comment]
![](https://desii.is-a-good-waifu.com/26a5c5.png)

**Comment by cgodon** [comment]
Marriage ends the timer prematurely
It wasn't 75 seconds before "time ran out" marry overrites the game timer remaining and ends it (starting a new timer for the "yes" "no"

**Comment by MrLar** [comment]
It indeed does, but It's intended behavior to avoid operations getting stuck.

**Comment by Kodehawa** [comment]
I'll leave this open so I can reference this when we fix it though.

Basically this is a workaround that needs to be fixed someday tm
