### ISSUE TITLE
>iam list not working properly

### ISSUE THREAD

**Issue by fuyukikoneko** [Mantaro/MantaroBot#111]
This has been happening since there was a problem viewing the server roles at the hastebin site 
(1 month), and you went back at showing them from mantaro and not hastebin.
Some of them get mixed with each other, even though they were put the right way when added as self assignable roles.We don't necessarily see the same roles getting mixed up every time, but various ones.

![screenshot 267](https://user-images.githubusercontent.com/31383358/35402190-7e385e8c-0204-11e8-914a-8aef2f8484ef.png)

**Comment by MrLar** [comment]
This is a visual only bug within Discord leaving and re-entering the channel will fix the visual aspect of the text.

**Comment by MrLar** [comment]
It happens when Markdown text is edited too fast and your client cant update it fast enough so the text gets inserted instead of actually edited leaving what you see in your screenshot.

**Comment by fuyukikoneko** [comment]
well yes, I know it's visual only, but it doesn't get fixed by re-entering the channel
not even after reloading discord

**Comment by MrLar** [comment]
🤔 can you DM me an invite to the server? MrLar#8117

**Comment by fuyukikoneko** [comment]
I can't seem to find you, can you DM me? to give you the invite
![screenshot 268](https://user-images.githubusercontent.com/31383358/35408367-789217c6-0217-11e8-9e22-bd6914b257ef.png)

**Comment by fuyukikoneko** [comment]
Fuyuki#6405

**Comment by MrLar** [comment]
Thats because we dont share servers you shouldve send a FR before hand, I send you one tho

**Comment by MrLar** [comment]
After investigating the server it was exactly what I said and it reset back to normal for them aswell. Since this is a bug on discords end we cant fix it therefor im closing this.
