### ISSUE TITLE
->opts music channel clear

### ISSUE THREAD

**Issue by gtc122004** [Mantaro/MantaroBot#116]
idk if this is the command I'm looking for, but I set the music channel to music, and now I want to have Mantaro in different channels. But this command isn't working and I don't want to reset the configuration.
![screenshot 1103](https://user-images.githubusercontent.com/28969308/35804499-1d60cbcc-0a46-11e8-9102-a23ecc3b9801.jpg)

**Comment by Kodehawa** [comment]
This will get fixed in next hotfix release (give it a day or two)

**Comment by Kodehawa** [comment]
I'm legit laughing at myself right now, but the "correct" command is `~>opts music channnel clear`

Yep, with three (3) `n

**Comment by MrLar** [comment]
kode pls

**Comment by gtc122004** [comment]
ya sorry I didn't know this one actually sent
