### ISSUE TITLE
music

### ISSUE THREAD

**Issue by muastacheman0158** [Mantaro/MantaroBot#118]
there is a problem when i were to use the music command right after using it, mantaro would join say there is a problem with the track and leave every time i would use the command

**Comment by justPPPPP** [comment]
You have to read #announcements. You can use Soundcloud for now, b'cuz it's Youtube's fault.

**Comment by MrLar** [comment]
![](https://desii.is-a-good-waifu.com/0dc489.png)
From our server announcements, but yea it's a youtube issue that we will be able to fix either later today or tomorrow

**Comment by MrLar** [comment]
It's highly suggested to join our [support server](https://discord.gg/BENsmmY) if you want live updates.

**Comment by justPPPPP** [comment]
*I have to turn off notifications from Github, 'cuz my inbox is full of junk. Rip*
