### ISSUE TITLE
Major Enhancement: Update AniList API to v2

### ISSUE THREAD

**Issue by edisonlee55** [Mantaro/MantaroBot#119]
**AniList will shutdown v1 API on May 1, 2018 ([AniList APIv1 documentation](https://anilist-api.readthedocs.io/en/latest/)).**

I look into the code [AnimeCmds.java](https://github.com/Mantaro/MantaroBot/blob/development/src/main/java/net/kodehawa/mantarobot/commands/AnimeCmds.java) noticed that Mantaro is still using v1 API, it will be an issue when AniList shutdown v1 API, and will need update to v2 API.

**Comment by MrLar** [comment]
Its already on our list for 5.0

**Comment by Kodehawa** [comment]
leave this open so we can claim fixed on the commit

**Comment by natanbc** [comment]
This has been implemented in #138 (not merged yet)
