### ISSUE TITLE
Database Rewrite

### ISSUE THREAD

**Issue by adriantodt** [Mantaro/MantaroBot#12]
Database uses too much reading because we filter stuff with regex.

This issue will track:

- [x] Rewrite of how we handle objects (POJOs)
- [x] Use snowflakes as new IDs
- [x] Create a MantaroDataPorter to fix the keys

**Comment by adriantodt** [comment]
Started working at 1 (Rewrite of how we handle objects (POJOs)) and 3 (Create a MantaroDataPorter to fix the keys)

**Comment by adamint** [comment]
simple fix: don't regex everything

**Comment by adriantodt** [comment]
After months of commiting and a branch recreation, the only thing left is:
- [ ] Update the codebase to use the new Entities

**Comment by adriantodt** [comment]
@Kodehawa your turn :^)

**Comment by Kodehawa** [comment]
On-hold for "manual" merge (probably after?) #51 (and therefore #52)
