### ISSUE TITLE
enhancement: Allow if else to be used inside another if else

### ISSUE THREAD

**Issue by gtc122004** [Mantaro/MantaroBot#120]
@if{@if{$(event.message.raw);equals;hi;ok}@if{$(event.message.raw);equals;ok;hi};not-equals;;correct argument;incorrect argument}
Would return correct argument if the user says ->cmd ok or ->cmd hi and incorrect if they don’t

**Comment by MrLar** [comment]
If-chains do not work properly with else's basically the else is ALWAYS fired.

**Comment by MrLar** [comment]
for more info check your [Documentation](https://github.com/Mantaro/MantaroBot/wiki/Custom-Commands#lets-go-to-the-actual-final-level-conditional-customs)

**Comment by MrLar** [comment]
But yea we do have better custom commands planned so for the enhancement part its coming just different cc #89

**Comment by gtc122004** [comment]
how would I do something like that above?

**Comment by MrLar** [comment]
You cannot currently

**Comment by gtc122004** [comment]
oh ok so I gotta wait for the next update
