### ISSUE TITLE
Bug Fix: ~>opts autorole set (role) won't work with roles that have spaces.

### ISSUE THREAD

**Issue by gt-c** [Mantaro/MantaroBot#125]
Will return "✖️ I couldn't find a role with that name".

**Comment by ASliceOfHammy** [comment]
Try putting the role in quotes "like this"

**Comment by Kodehawa** [comment]
Fixed in 5.0, waiting for release.

**Comment by Kodehawa** [comment]
For now, do what's on the comment above the comment before this one.
