### ISSUE TITLE
enhancement: random level up/join/leave messages

### ISSUE THREAD

**Issue by gt-c** [Mantaro/MantaroBot#129]
Kind of like what happens when you run ~>custom add, a bunch of user set options that the bot randomly picks from.

**Comment by natanbc** [comment]
@Kodehawa

**Comment by Kodehawa** [comment]
maybe?

**Comment by natanbc** [comment]
We could implement this like we do for multiple responses in custom commands

**Comment by Kodehawa** [comment]
yah, will get on it tonight

**Comment by natanbc** [comment]
This has been implemented in the latest commit, and will be deployed as of 5.0
