### ISSUE TITLE
Custom command images

### ISSUE THREAD

**Issue by Pigletti** [Mantaro/MantaroBot#133]
When I go to make a custom command with an image, the image won’t show up. I’m not sure if it’s a bug or I’m doing something wrong but I’ve typed in the right command multiple times, I don’t know what’s up.

**Comment by natanbc** [comment]
What's the command you added?

**Comment by Pigletti** [comment]
->custom add Elmo imgembed: (then the photo link)

That’s what I entered to add, I deleted the command I added which was just ->Elmo and a couple times when retrying to add the command I would also do it lower case ->elmo 

(I’m also doing this elmo command for a friend I know it’s weird)

**Comment by Desiiii** [comment]
Was the image a direct link? (for example, ends with `.png`, `.gif`, `.jpg` etc) If it's not a direct link, the image wont show in the embed.

**Comment by Pigletti** [comment]
https://goo.gl/images/D7R9Ku

**Comment by Kodehawa** [comment]
thats not even close to a direct link

**Comment by Pigletti** [comment]
Would imgur work for a direct link?

**Comment by natanbc** [comment]
this is what a direct link looks like `https://i.imgur.com/2PS9xSJ.jpg`
