### ISSUE TITLE
Reputation Badges and Items

### ISSUE THREAD

**Issue by MrZekeM** [Mantaro/MantaroBot#135]
Was wondering if we could get reputation badges and items as currently reputation doesn't really do much, so maybe a badge at 10 rep then 100 rep and earn rep items in a 1/50 chance.

Picture to show what i mean about reputation.
![profile](https://user-images.githubusercontent.com/37345371/37363187-31fa2234-26ef-11e8-956e-500ba2c77033.PNG)

**Comment by natanbc** [comment]
@Kodehawa

**Comment by Kodehawa** [comment]
I'll get to doing this, @MrLar add to trello please.

**Comment by MrLar** [comment]
We have added reputation related badges in 5.0, aswell as reputation plays a huge role in the new Waifu system. Documentation for both is pending (for further info join the [support server](https://support.mantaro.site))
