### ISSUE TITLE
Custom Command

### ISSUE THREAD

**Issue by DarkFireGuy** [Mantaro/MantaroBot#136]
I've got a server with friends and we just did ->marry with each other cause it's funny. Now we wanna add a custom command that that would be typed like this: ->fuck @insertPersonHere and it would display "personWhoUsedTheCommand fucked personWhoTheCommandWasUsedOn" and display a gif of our choice. I really don't know how I would do this, any help would be appreciated!

**Comment by natanbc** [comment]
https://github.com/Mantaro/MantaroBot/wiki/Custom-Commands

also ( ͡° ͜ʖ ͡°)
