### ISSUE TITLE
$(event.author.mention) inside of embed:

### ISSUE THREAD

**Issue by DarkFireGuy** [Mantaro/MantaroBot#137]
=custom new fuck embed:title:"$(event.author.mention) has just fucked $(event.message.raw)",image:"https://myanimelist.cdn-dena.com/s/common/uploaded_files/1483510519-2be851ce5a8c0d3b3b299ceb99f2f5aa.gif"

when $(event.author.mention) is inside of the embed thing it returns a<@!355883064934793217> instead of the users name.
How do I get it to return the user?
P.S. this is for a server that me and my friends are on and we need to make a fuck command cause it's funny

**Comment by natanbc** [comment]
https://github.com/Mantaro/MantaroBot/wiki/Custom-Command-Modifiers

**Comment by natanbc** [comment]
Mentions only work in embed description and field values (except on mobile, where they don't work at all)
