### ISSUE TITLE
~>play soundcloud issue

### ISSUE THREAD

**Issue by KnifuWaifu** [Mantaro/MantaroBot#139]
When you say ~>play, Mantaro will describe the command.
![screenshot 315](https://user-images.githubusercontent.com/37506151/37566489-21d3fa48-2a77-11e8-8b4d-bbad82dd850a.png)
But when you say ~>play soundcloud, Mantaro will search songs that has no correlation at all.
![screenshot 316](https://user-images.githubusercontent.com/37506151/37566509-6aaa8624-2a77-11e8-8a99-acb5ed916893.png)

**Comment by KnifuWaifu** [comment]
btw dont worry about the bot's name that wasn't me, it was just some random prank. ;-;

**Comment by MrLar** [comment]
Minor but still technically bug so I'll forward it 👍

**Comment by natanbc** [comment]
~>play souncloud **<search term>**

**Comment by KnifuWaifu** [comment]
There is some pattern with the suggested songs, I tried it again and different songs show up, it might be someone's soundcloud listening history.

**Comment by Kodehawa** [comment]
That's just youtube wanting to give a match so it tries searching for ocurrences on the song descriptions
