### ISSUE TITLE
~>trivia issue

### ISSUE THREAD

**Issue by KnifuWaifu** [Mantaro/MantaroBot#140]
When you say ~>trivia during a trivia session that you opened up, Mantaro will act like no trivia session happened at all.
![screenshot 321](https://user-images.githubusercontent.com/37506151/37578556-ee5b8c3c-2af6-11e8-8382-e7ae0ff30a28.png)

**Comment by Kodehawa** [comment]
That's the ratelimit message, what are you talking about?
That has nothing to do with a session on or no, it just tells you the entire command is in cooldown and it won't execute until that time in there passed by

**Comment by Kodehawa** [comment]
Try... I don't know, actually waiting and seeing what message appears (hint hint: it will say there's a session going on)

**Comment by KnifuWaifu** [comment]
Oh fuck I put the wrong screenshots sorry. lol But in my server me and some other guy somehow opened up two trivia sessions for different people at the same time.

**Comment by Kodehawa** [comment]
Just tested it, it shouldn't happen
![here](https://user-images.githubusercontent.com/20606963/37627585-dc3c17ac-2bb3-11e8-812c-e599710273f9.png)

**Comment by KnifuWaifu** [comment]
Hmmmmm. Ima try it again.

**Comment by KnifuWaifu** [comment]
Oki it gud now UwU

**Comment by Kodehawa** [comment]
weird, I'll leave it open and if it happens again send me a picture here.

If it doesnt happen in some weeks I'll close it.

Thanks you~
