### ISSUE TITLE
Enhancement :P

### ISSUE THREAD

**Issue by KnifuWaifu** [Mantaro/MantaroBot#141]
[BY THE WAY, I WAS GONNA MAKE A PULL REQUEST FOR THIS BUT I AM A BIT RUSTY WITH JAVA AND IT WOULD BE EASIER IF Y'ALL DO IT SO YOU GUYS DON'T SPEND TIME TURNING C++ INTO JAVA]

So... It would be cool when you level up, Mantaro would say something like "Yay! Congrats, <player-name>! You leveled up!", and then Mantaro shows the number you leveled up to. I am requesting this because most people in many servers INCLUDING the mantaro hub don't know that there are levels for the Mantaro Bot. Y'all don't have to do it but, hey, it would be interesting to put in. 
*kisses*

**Comment by Kodehawa** [comment]
That is a thing. Please check the wiki to see how to enable it (cc: level-up messages)
