### ISSUE TITLE
JSON parsing for custom commands (fields) is bugged

### ISSUE THREAD

**Issue by isaaclo123** [Mantaro/MantaroBot#145]
When using embeds in if statements, the json parsing is bugged.

When running the command

```-custom new merchstore @if{$(event.message.raw);equals;;embed:description:"test",fields:[{name:"Items",value:"1. item1"}]}```

the custom json is parsed as

```The string {description:"test",fields:[{name:"Items",value:"1. item1"]}} isn't a valid JSON.```

![correctfails](https://user-images.githubusercontent.com/9246180/37928597-ee2787e0-3102-11e8-956b-6445c9838c94.png)

On the other hand, if one creates a command with invalid json, it succeeds

```-custom new merchstore @if{$(event.message.raw);equals;1test;embed:description:"test",fields:[{name:"Items",value:"1. item1"}},]```

![buggedworks](https://user-images.githubusercontent.com/9246180/37928628-0583707a-3103-11e8-97d5-c3e495d2f305.png)

**Comment by natanbc** [comment]
The [current implementation](https://github.com/Mantaro/MantaroBot/blob/development/src/main/java/net/kodehawa/mantarobot/commands/custom/ConditionalCustoms.java) of ifs uses regex, which can't handle this case. There will be a new type of custom commands in the future which will allow this.
