### ISSUE TITLE
Sry not an issue just an idea and i dont know where to put ideas

### ISSUE THREAD

**Issue by falltman** [Mantaro/MantaroBot#149]
So me and my server love your bot, but we sometimes wish we could chose the ~>hug images or the other ~> action commands because sometimes they dont fit the mood. So my idea was that when someone does the action command it would delete the comment (or not doesn't matter) then it would pop up in a private chat or something and it will give some options with numbers next to them. Then you would type the number and that will be the image that will pop up. Thanks if you actually read this. If you can plz get back to me on what you think. 
Thanks

**Comment by MrLar** [comment]
Sorry for the late reply but we basically have 0 control over what image we get during action commands, we hit up a third party API to request a random image.
