### ISSUE TITLE
Ownmake psychopass custom command.

### ISSUE THREAD

**Issue by Szadav** [Mantaro/MantaroBot#154]
I would like to know if it is possible to make custom command like a psychopass (useless but so much fun). I wish to do it myself one.

First, needed a random between 0 to 1000 (unity %), do we have a $(random*1000) ? 

~>psychopass @someone
M:embed: @someone psychopass is %
IF <100 : Suspect is not a target for enforcement action. The trigger of Dominator will be locked.
IF <299 : Suspect is classified as a latent criminal and is a target for enforcement action. Dominator is set to Non-Lethal Paralyzer mode. Suspect can then be knocked out using the Dominator.
IF =<1000 :  Suspect poses a serious threat to the society. Lethal force is authorized. Dominator will automatically switch to Lethal Eliminator. Suspect that is hit by Lethal Eliminator will bloat and explode.

Can figure some action in each case. Oh sometimes even if the psychopass is <299 we really want to kill him, forcing dominator in lethal will be great Xþ

**Comment by MrLar** [comment]
This is currently not possible due to the limitations of custom commands version 1. However it might be possible in version 2 whcih will be released along side Mantaro version 5.0

**Comment by Szadav** [comment]
Wait and see then.
Ty
