### ISSUE TITLE
Crash Reset

### ISSUE THREAD

**Issue by Pokeeee** [Mantaro/MantaroBot#156]
Discord Name:Pokeeee#1921
So basically whenever the bot does a restart all cooldown are reset so life if you have 10x days for ~>daily, when the bot does a reboot you can use ~>daily again for 11x days when 24 hours didn’t pass yet, same for ~>rep ~>loot ~>mine and other commands that require cooldown

**Comment by ASliceOfHammy** [comment]
The bot doesn't save cooldowns when it restarts so all cooldowns are reset

**Comment by MrLar** [comment]
This is intentional
