### ISSUE TITLE
allow certain roles to use moderation commands?

### ISSUE THREAD

**Issue by whattheshark** [Mantaro/MantaroBot#157]
the wiki says only people with admin permissions can use moderation commands, so does that mean a role without admin perms but with kick/ban perms can't use the bot moderation commands?

is there a way to give certain roles permissions to moderate with commands?

**Comment by MrLar** [comment]
Moderation Commands are bound to their respective permissions the Admin thingy mentioned in the Wiki only applies to Opts and that one is usable by anyone who has Manage Server or a role called "Bot Commander"

**Comment by whattheshark** [comment]
so if i'm understanding correctly: a role with kick, ban, mute will be able to use the bot commands to perform those actions?

and if i make another role called Bot Commander and give that to people they can have access to Opts?

**Comment by MrLar** [comment]
Mute is a bit special mute requires you to have Ban and kick (which is a bug that will be fixed and it will soon require only one of the two), as mute is not a Voice Chat mute so tying it to the Mute permission wouldn't make sense other than that you got that perfectly right

**Comment by whattheshark** [comment]
thank you, i very much appreciate the help!
