### ISSUE TITLE
Rigged trivia question

### ISSUE THREAD

**Issue by n8dm** [Mantaro/MantaroBot#160]
![image](https://user-images.githubusercontent.com/38740046/39278558-5635950c-48a0-11e8-9565-e786162dc27b.png)
I'm not sure if google is correct, but I figured dogs were first so I looked it up, and
![image](https://user-images.githubusercontent.com/38740046/39278584-80f54b52-48a0-11e8-9208-be767bc30e95.png)

**Comment by n8dm** [comment]
![image](https://user-images.githubusercontent.com/38740046/39278614-a3ed9ace-48a0-11e8-9e7b-403ccf47cb46.png)
alright i'm stupid

**Comment by Desiiii** [comment]
Also for future reference, Mantaro does not have any affect on the trivia questions, as they are provided by an external source. To report bugs in trivia question content, report them [here](https://opentdb.com/).
