### ISSUE TITLE
Custom command target modifiers

### ISSUE THREAD

**Issue by Vojevudce** [Mantaro/MantaroBot#161]
Hello there,
I was looking for creating custom commands same as your !cuddle @user and such. Output on these are random gifs + short text, like "@user1 cuddles @user2", but when I look at modifiers, I see only those that refer to command author, but nothing like "target user" or "target mention". Am I blind? :D 

Thanks for help
peace
Vojevudce

**Comment by MrLar** [comment]
You cannot target mentions in the current version of custom commands the closest you will get is event.message.raw

**Comment by Vojevudce** [comment]
Will it ever be added? I would really appreciate it. + Is there a way to randomize gif output? Like when I do custom !blush, it outputs one from 5 saved gifs?
Btw. thanks for quick reply, you rule!
