### ISSUE TITLE
Facepalm command

### ISSUE THREAD

**Issue by ReddieEX** [Mantaro/MantaroBot#163]
Hey there!

is there any way to add a facepalm command for images eg. http://i0.kym-cdn.com/photos/images/newsfeed/000/173/877/Facepalm.gif to the bot?

**Comment by MrLar** [comment]
embed:description:"$(event.author.name) is face-palming..",image:"http://i0.kym-cdn.com/photos/images/newsfeed/000/173/877/Facepalm.gif"

Is the closest you will get with whats currently possible

**Comment by MrLar** [comment]
As custom command that is you can check more regarding that by clicking the "wiki" on the top of the page. And the navigate to the understanding custom command section

**Comment by ReddieEX** [comment]
tought something like the action commands where random images got picked

**Comment by MrLar** [comment]
Yea you can do that you can add multiple responses with different image urls everytime and Mantaro will pick one at random
