### ISSUE TITLE
Rework the -daily command

### ISSUE THREAD

**Issue by Sealestr** [Mantaro/MantaroBot#164]
Make the `-daily` command be able to be executed on any time during a day rather than have a 24 hr cool-down. Currently, the command forces me to stay up late in order to be able to claim the reward, which isn't convenient.

**Comment by MrLar** [comment]
Being able to execute it any time during the day would effectively eliminate the idea of Daily streaks, as currently for your streak to continue you have to do it again after ~25 hours (~1 hour of tolerance). If you would make it a one use/day command with not actual cool down you could just use it any time during the day to continue your streak effectively not punishing users that simply forgot unless they forgot for a full day. However decision is up to @Kodehawa

**Comment by Kodehawa** [comment]
The streak resets only if you miss two days in a row. The grace period is more than enough and I'm pretty sure you don't nees to stay late, just do it at the morning
