### ISSUE TITLE
Retrieving Images

### ISSUE THREAD

**Issue by SakuSakuCoco** [Mantaro/MantaroBot#174]
Our Mantaro bot has been having issues with getting animal images.
For example, we like to use different bots for different cute cat images, but the Mantaro bot has been saying "Error retrieving cute cat images :<" for a few months now.
Is anyone else having this problem?
What can we do to fix it? Thank you!

![screenshot 2018-06-15 at 8 09 04 am](https://user-images.githubusercontent.com/40296371/41467167-67eb2672-7073-11e8-88f2-cbbe4e5ce438.png)

**Comment by MrLar** [comment]
This is a known issues that occurred due to the third party service that we used becoming unavailable and/or having changed how to retrieve images drastically. This will be fixed in either a feature update or the upcoming 5.0 release.

**Comment by SakuSakuCoco** [comment]
Okay, thank you!

**Comment by MrLar** [comment]
This has been fixed with the release of 5.0
