### ISSUE TITLE
Multiple marriages

### ISSUE THREAD

**Issue by etattershall** [Mantaro/MantaroBot#178]
Is there any chance we could get multiple marriages? Monogamy is hard :sweat_smile:

**Comment by Desiiii** [comment]
I mean, there is a waifu system coming in version 5.0, which is currently in development, so it is kinda like that.

**Comment by MrLar** [comment]
To add onto that its been requested many times which is why we are adding this waifu system. Though to my knowledge we have no intentions to support actual marriages with multiple people. This may changed in the future though.
