### ISSUE TITLE
Multiple replies

### ISSUE THREAD

**Issue by test512b** [Mantaro/MantaroBot#18]
How do I make multiple replies in custom commands work with :img? Because it seems to only work with the first reply.
Also how do I make the bot mention someone I mentioned in a custom command? For example: ~>highfive @user

$(event.author.mention) high fived @mentioneduser

**Comment by Kodehawa** [comment]
You can use `$(event.message.raw)` to capture the message. 
Also multiple replies should work, remember to separate them properly with `;`

Awaiting a response regarding the `img:` problem you described if that doesn't fix it.

**Comment by Kodehawa** [comment]
Closing since no reply.

**Comment by test512b** [comment]
Thanks for replying! And sorry for the late response.
The multiple replies does work but not properly with img: (only the first reply gets the image embed and the rest comes with the "img:" text.
And just wondering if there is a way to add like a condition for the highfive command, like when no users are mentioned.
Again, thanks a lot!

**Comment by Kodehawa** [comment]
highfive will be an actual command soon btw

**Comment by Kodehawa** [comment]
if anyone gets this, remember to leave no space between one and another reply and the separator
http://i.imgur.com/9ZqRvpL.png for example

**Comment by Mxchyz** [comment]
Michy - Today at 4:09 PM
->custom new test embed:title:"test",description:"testing";embed:title:"test2",description:"testing2"

MantaroBOT - Today at 4:09 PM
:white_check_mark: Saved to command test!

Michy - Today at 4:09 PM
->test

MantaroBOT - Today at 4:09 PM
:x: The string **{title:"test",description:"testing";embed:title:"test2",description:"testing2"} isn't a valid JSON.** 
@Kodehawa Help?

**Comment by natanbc** [comment]
Use `~>custom new <name> <response 1>` and `~>custom add <name> <new response>` to add more responses

**Comment by MrLar** [comment]
Refer to [this](https://github.com/Mantaro/MantaroBot/wiki/Custom-Commands) for more detailed info on how customs work.

**Comment by Desiiii** [comment]
The `;` separator for custom commands was removed months ago, so this did once work. Just saying this to prevent confusing
