### ISSUE TITLE
Mantaro in voice chat but no music is playing

### ISSUE THREAD

**Issue by Mitsukaritas** [Mantaro/MantaroBot#180]
I hope this was the place to report this, here are the ~>info shards <br>
Shard [120 / 144] <br> thanks in advanced

**Comment by natanbc** [comment]
what track are you playing? is it paused? did you try leaving the voice channel and rejoining (you, not the bot)?

**Comment by Kodehawa** [comment]
did you try using stop and summoning it again, tried pause to unpause it, etc?

**Comment by Mitsukaritas** [comment]
yes

**Comment by Kodehawa** [comment]
Rebooted shard. For any further inquiries please check https://support.mantaro.site
