### ISSUE TITLE
$(event.user) error/bug?

### ISSUE THREAD

**Issue by SirSpektre** [Mantaro/MantaroBot#181]
Our server's welcome message randomly fails to mention the new user who joined, and it happens frequently. 
![image](https://user-images.githubusercontent.com/40806295/42240477-70f46dd0-7ed5-11e8-8ea2-31247c93f1f9.png)

Those numbers don't act as a link to the user, and it's obvious that we still want the name to show. It used to always work, and now it just randomly does that^ sometimes and we didn't change the command.

**Comment by Kodehawa** [comment]
Discord's fault. Switch to name#discrim if you don't want this to happen, we cannot do anything.

**Comment by SirSpektre** [comment]
Can I ask where that switch is made? Like am I looking for $(event.user.name#discrim) or something?

**Comment by MrLar** [comment]
$(event.user.username)#$(event.user.discriminator)

**Comment by MrLar** [comment]
You can always check [this](https://github.com/Mantaro/MantaroBot/wiki/Custom-Command-Modifiers) for a list off all available modifiers

**Comment by SirSpektre** [comment]
I was still hoping to get the mention to work 100% of the time, which I guess isn't possible. Thanks for the help anyway though!

**Comment by MrLar** [comment]
Pretty much impossible due to discord simply being inconsistent at times
