### ISSUE TITLE
How to make the same command as montaro actions command

### ISSUE THREAD

**Issue by BJladika** [Mantaro/MantaroBot#185]
Hi, I want to make a few command, the same as action commands (like a ->bloodsuck, etc), but its really strange thing, like how imgembed works?
I just tried smth like this:
->custom new batarang $(event.author.name) has throwed batarangs to $(event.message.stripped)! imgembed:[url link]
But this imgembed didnt dissapear from the messages

Can you lets say, give me a like template of such action commands? (different random images, text, etc)

**Comment by MrLar** [comment]
Since you cannot actually attach files like mantaro and there are no modifiers for mentions the closest you will get is using an embed (embed:description:"your text here",image:"your direct image url here")

**Comment by MrLar** [comment]
The quotes in my example are important btw and afaik imgembed: is broken and it also cannot be combined with text. And i should probably also mention that you cannot combine and embed with actual text hence why my example has the description part.
