### ISSUE TITLE
Mantaro Money

### ISSUE THREAD

**Issue by Yuno-Gasai** [Mantaro/MantaroBot#186]
Good day. Or Good Evening. I wanted to ask if you can add money to Mantaro. Because one of them wrote "~> Money24" and got 240000 coins and this is not honest because of himself 
![img_20180721_151014](https://user-images.githubusercontent.com/41512233/43035966-38883d4c-8cf8-11e8-81c9-1f1a88adcbb5.png)

**Comment by MrLar** [comment]
This is a custom command that __fakes__ giving you credits, there is no way to add money to your or anyone else withotu actually transferring it

**Comment by MrLar** [comment]
tl;dr no theres no way to give money and that command is just a fake
