### ISSUE TITLE
Badges not appearing.

### ISSUE THREAD

**Issue by DifferentCity** [Mantaro/MantaroBot#189]
There seems to be an issue with items and badges not appearing in Discord.
I am hoping these appear and you can see the images. 
![screenshot_20180727-232125](https://user-images.githubusercontent.com/41811392/43352615-2964b92a-91f4-11e8-83b9-6b8d4a7f0252.png)
![screenshot_20180727-232149](https://user-images.githubusercontent.com/41811392/43352618-30f9eb74-91f4-11e8-82e7-783b16cfe240.png)
![screenshot_20180727-232246](https://user-images.githubusercontent.com/41811392/43352619-3597937a-91f4-11e8-90b9-d6a5b1ee4924.png)
![screenshot_20180727-232248](https://user-images.githubusercontent.com/41811392/43352620-39af1dac-91f4-11e8-8dc5-070f0a464b54.png)

**Comment by MrLar** [comment]
You may have missed this line
 ![](https://desii-is-the-love.of-my.life/132209.png)

All badges apply after you do the profile command they do NOT immediately show up when doing badges. This is intended.

**Comment by DifferentCity** [comment]
We have done this. The badge for 5k items does not appear still. I had
gotten 5k items before and done the profile command it never appeared.

**Comment by DifferentCity** [comment]
Just double checked. An error on my behalf. I apologize.
