### ISSUE TITLE
Game command glitched?

### ISSUE THREAD

**Issue by Lightking124** [Mantaro/MantaroBot#19]
There is a glitch where the bot thinks it is in a game, but not only did the "end" not work, but it's been almost a day and still doesn't timeout.  Is there a way to reset it so we can play our games again?  I tried kicking her and re-adding her, that didn't work either...

**Comment by Kodehawa** [comment]
~>opts lobby reset

**Comment by Lightking124** [comment]
That worked, thank you~!

**Comment by Kodehawa** [comment]
Added to documentation now. np <3
