### ISSUE TITLE
ignore bot-command temporarily 

### ISSUE THREAD

**Issue by Beljiah** [Mantaro/MantaroBot#193]
Hey, is it possible
One way to use a command or costum command to ignore all bot commands in the current channel for a certain amount of time.(A Timer like ~>remindme)
I would like to give users the opportunity to ignore bot commands temporarily so that, for example, a discussion is not disturbed. Without ignoring the channel permanently

**Comment by MrLar** [comment]
Not possible as of now up to @Kodehawa whenever or not it's added
