### ISSUE TITLE
typo in commands wiki

### ISSUE THREAD

**Issue by urthurao** [Mantaro/MantaroBot#197]
typo in currency commands, command 5, example 4. (items.items)
![command_reference_and_documentation_ _mantaromant_2018-09-08_19-26-56 492_3ahxeccvz7](https://user-images.githubusercontent.com/28652175/45252705-6b3a7d00-b39e-11e8-9110-14dbcfa62591.png)

**Comment by MrLar** [comment]
This is gonna get fixed along side the update the wiki

**Comment by MrLar** [comment]
This has been fixed.
