### ISSUE TITLE
mantaro sends images but without preview

### ISSUE THREAD

**Issue by Mair3x** [Mantaro/MantaroBot#198]
i tried using some image commands like ->catgirl o others but mantaro sends 
something like links with png at the bottom and other 
![screenshot_20180909-012441](https://user-images.githubusercontent.com/43101113/45259534-6fcb5980-b3cf-11e8-95ee-69664da7785f.png)
i tried entering that link but what i see is Nothing
![screenshot_20180909-012805](https://user-images.githubusercontent.com/43101113/45259538-a43f1580-b3cf-11e8-834e-eca34fc0b35c.png)
pls help

**Comment by MrLar** [comment]
Go to your user settings (cog in the bottom left next to your username) -> test & images
go to "show images when..." and tick "when uploaded directly to discord".
This syncs with mobile & all other clients, your can disable syncing on any mobile device in the same menu.

**Comment by MrLar** [comment]
Closing due to no further activity
