### ISSUE TITLE
Birthday Announcer Command

### ISSUE THREAD

**Issue by JenThePenguin** [Mantaro/MantaroBot#201]
Hello, I've been having issues trying to enable the birthday announcer on my server. I've followed the documentation exactly, but when I try to do the test, I receive this message, "The bot is unable to interact with the birthday role." I wasn't sure how to fix it.

**Comment by MrLar** [comment]
It means that the Bot is either missing `Manage Roles` as permission *or* that the role you set as birthday role has a higher hierarchy (higher order in the role manage menu) than Mantaro's highest role.

**Comment by JenThePenguin** [comment]
Thank you very much! I totally forgot role hierarchy mattered on discord. I assumed that since Mantaro was an admin, it would bypass the hierarchy. I haven't used it in awhile... I appreciate the quick response!
