### ISSUE TITLE
I just fricked myself over. I accidentally disabled the moderation commands, and now i cant re-enable them.

### ISSUE THREAD

**Issue by FireballFoxtrot** [Mantaro/MantaroBot#203]
How can i re-enable the moderation commands? i've tried to kick and rejoin mantaro, but the bot keeps the config and i just cant figure out how to re-enable the commands!

**Comment by Kodehawa** [comment]
Give us the guild id and I'mma restore it. Gonna fix it later whenever I get back home

**Comment by FireballFoxtrot** [comment]
490338901169405964

**Comment by MrLar** [comment]
Should be fixed, don't do it again though 👍

**Comment by FireballFoxtrot** [comment]
i got a suggestion: make a warning message when you attempt to disable moderation commands so big dumbs like me dont do this lol

**Comment by Kodehawa** [comment]
it shouldn't be possible, i memed out and now it is and im gonna fix it w/a new version whenever i get home

**Comment by MrLar** [comment]
Besides there currently is a large warning in the wiki

**Comment by Kodehawa** [comment]
Fixed as of latest
