### ISSUE TITLE
`time` supports UTC, but `profile timezone` does not

### ISSUE THREAD

**Issue by numbermaniac** [Mantaro/MantaroBot#205]
![screen shot 2018-09-18 at 8 48 12 am](https://user-images.githubusercontent.com/5206120/45654610-c8ad9700-bb1f-11e8-8f7e-4278c29692cd.png)
![screen shot 2018-09-18 at 8 48 17 am](https://user-images.githubusercontent.com/5206120/45654611-c8ad9700-bb1f-11e8-93aa-088570e6ae16.png)
![screen shot 2018-09-18 at 8 48 32 am](https://user-images.githubusercontent.com/5206120/45654612-c8ad9700-bb1f-11e8-9383-1310550a94fe.png)

Notice how `time` supports UTC, but `profile timezone` doesn't support UTC for some reason, only GMT.

**Comment by Kodehawa** [comment]
Will be fixed on next release, sorry for forgetting about this.
