### ISSUE TITLE
Character Game Error: Stephanie Dora

### ISSUE THREAD

**Issue by CrystalCruse** [Mantaro/MantaroBot#206]
Used ->game character and was replied with ":warning: Report this in the official server please. Failed to setup game for pre-saved character: Stephanie Dora"

screenshot: https://gyazo.com/b0e6f6f3e070e3c8e7248afe5cb81edd

**Comment by howdoicode5058** [comment]
known.mp3

**Comment by totallynotaidan** [comment]
known bug I'm p sure

**Comment by howdoicode5058** [comment]
dab
