### ISSUE TITLE
[ Feature Req. ] casting multiple items

### ISSUE THREAD

**Issue by gt-c** [Mantaro/MantaroBot#207]
allow casting of multiple items
e.g.
`~>cast diamond pickaxe -amount 10`
instead of saying `~>cast diamond pickaxe` 10 times.

if there already is a way to do this, plz let me know.

**Comment by Kodehawa** [comment]
Added to trello, expect for 5.1.x or 5.2. Gonna be a full-on system though, just not multiple casting for the default wrench (tiered wrenches)

**Comment by Kodehawa** [comment]
Added to 5.3. Live on MP, release soon enough.
