### ISSUE TITLE
help wanted: new items

### ISSUE THREAD

**Issue by Wuji2000** [Mantaro/MantaroBot#208]
im having some trouble with the new items, like the gem crate. i cant open it with the ~>opencrate (tried a opencrate gem, but it says its not a valid loot crate) and ~>useitem also doesnt work. the sparkle pick also isnt cooperating, mantaro says its not a valid number when trying to transfer it (dont know if its transferable 🤔).

**Comment by MrLar** [comment]
`~>opencrate mine crate` and sparkle pickaxes isnt fully implemented yet and itemtransfer syntax is `~>itemtransfer @mention amount item` (note some items cannot be transferred)

**Comment by Wuji2000** [comment]
ooh ok, thanks 😄
