### ISSUE TITLE
Music speed

### ISSUE THREAD

**Issue by Teal-chan** [Mantaro/MantaroBot#21]
For some reason, the bot is playing music at, like, 3x speed.
It's messing with our gameplay.

**Comment by Kodehawa** [comment]
Kick and re-add the bot. We're trying to figure this out with the guys at JDA (the ones who made the java library)

**Comment by Kodehawa** [comment]
Anyone else getting it?

**Comment by adamint** [comment]
in the meantime could we spin up a bunch of threads to periodically compare intervals to see whether x seconds of player time = x seconds as measured by the computer

**Comment by Kodehawa** [comment]
Reference: https://github.com/DV8FromTheWorld/JDA/issues/357

**Comment by KappaDarius** [comment]
I am getting the same problem

**Comment by Kodehawa** [comment]
Use ~>opts musicspeedup fix

**Comment by Kodehawa** [comment]
Seems fixed.
