### ISSUE TITLE
Special Pickaxes won't work

### ISSUE THREAD

**Issue by OrangTea** [Mantaro/MantaroBot#211]
So, yesterday I made a diamond pickaxe, and then I did "~>mine" and Mantaro responded "You don't have any pick to mine.", even though I had the diamond pickaxe. I haven't tested this with other pickaxes, but right now, only Brom's Pickaxe will allow me to mine.

**Comment by Kodehawa** [comment]
~>mine diamond pickaxe
~>mine d p 

you have a specify it

**Comment by Haxiz** [comment]
You need to use "->mine diamond pickaxe"
"->mine d p" works as well.
Same with all the other picks, you need to write the name after "->mine"
