### ISSUE TITLE
I received a LanguageKeyNotFoundException while trying to process the command. (internal error)

### ISSUE THREAD

**Issue by vieuxgnome** [Mantaro/MantaroBot#226]
When I try to use anime command, Manatro say : 
"I received a LanguageKeyNotFoundException while trying to process the command. (internal error)"

See in attachment.
![2018-11-18_00h26_10](https://user-images.githubusercontent.com/7295002/48666783-9fca6380-eac8-11e8-9c92-8e5d017e0246.jpg)

I already try to reset language with "profile lang reset"

**Comment by Kodehawa** [comment]
Known, will be fixed on next release

**Comment by MrLar** [comment]
fixed in 5.1
