### ISSUE TITLE
Guessing game is stuck.

### ISSUE THREAD

**Issue by johnxfire** [Mantaro/MantaroBot#23]
Basically this - user started a pokemon guessing game, and at one point Mantaro stopped taking his answers. Now no one can start a new game from the bot - I haven't tried kicking as I don't want to have to rework permissions on it. Any idea how to force terminate a game? I didn't see it in the command list.

**Comment by MrLar** [comment]
use the command ~>opts lobby reset

**Comment by MrLar** [comment]
also kicking and readding the bot would leave you permissions saved

**Comment by Kodehawa** [comment]
`~>opts lobby reset` fixes that completely, as lars said

**Comment by johnxfire** [comment]
Thanks - totally fixed!
