### ISSUE TITLE
No response ->Anime 

### ISSUE THREAD

**Issue by IcesyWisy** [Mantaro/MantaroBot#231]
Using command ->anime to search up for specific anime doesn't work proper.
If client have used that command they receive a list of that anime. If client press a number to choose out of that list, Mantaro doesn't give the information about that anime that client had choose.  
I have fully checked the permission of Mantaro, the bot is able to sent messages, files and embled links.
Is this a new feature or a fix?

![capture1](https://user-images.githubusercontent.com/45293128/49511328-259d2b80-f88b-11e8-9003-da46aa4ad287.PNG)

**Comment by MrLar** [comment]
This is a known issue that will be resolved in the next update (which we have no ETA for)

**Comment by MrLar** [comment]
fixed in 5.1
