### ISSUE TITLE
How do you fix the special Pickaxes??

### ISSUE THREAD

**Issue by P4DF00T** [Mantaro/MantaroBot#234]
So just made the diamond pickaxe and it broke, i noticed that broken special pickaxes are an actual item while broken normal pickaxes are not an item. was wondering if there is a way to fix the diamond pickaxe.

**Comment by MrLar** [comment]
Broken pickaxes as an item are a mere leftover collectible item there is no way to fix them. A pickaxe that breaks does **not** become a broken pickaxe (item), they simply disappear and its pure luck whenever or not they break.
