### ISSUE TITLE
Mantaro not joining voice channel for music

### ISSUE THREAD

**Issue by SirSpektre** [Mantaro/MantaroBot#235]
As per the FAQ#3 I'm reporting this for our server. Mantaro will queue music normally but will never join the voice channel, and then act as if there is no music queued. This issue started a few days ago.
![image](https://user-images.githubusercontent.com/40806295/50120743-d43e5600-0213-11e9-9e62-2c17ec286681.png)
![image](https://user-images.githubusercontent.com/40806295/50120748-da343700-0213-11e9-8084-f07ec616ef6e.png)
(yes the nickname is Heartbreaker)

If you guys can confirm any actions I can do on my end and/or what information I can get you that will help I'll gladly do what's necesssary. Also ~>info doesn't do anything so I'm not clear on what info you need. Shard info is the only thing that came to mind.
![image](https://user-images.githubusercontent.com/40806295/50120970-8f66ef00-0214-11e9-923a-be03d4416193.png)

**Comment by Kodehawa** [comment]
Join the support server at https://support.mantaro.site so we can provide further help.

**Comment by Kodehawa** [comment]
Also try changing your voice region and report back

**Comment by MrLar** [comment]
seems to be a dead issue closing.
