### ISSUE TITLE
yyyy-MM-dd

### ISSUE THREAD

**Issue by khonkhortisan** [Mantaro/MantaroBot#24]
https://xkcd.com/1179/
https://en.wikipedia.org/wiki/ISO_8601
~>birthday 1999-12-31

**Comment by MrLar** [comment]
It doesn't go by ISO 8601 the correct format is dd-mm-yyyy

**Comment by Kodehawa** [comment]
nice XKCD reference but we go with the format everyone uses except the US and some other countries
I could add it later, but closed for now

the US is a special snowflake
would you like some metrics with your order?

**Comment by Kodehawa** [comment]
in a more serious note we will add it later

**Comment by khonkhortisan** [comment]
The US uses mm/dd/yyyy, otherwise it's dd/mm/yyyy. Afaik dashes are only used for yyyy-mm-dd.

**Comment by Kodehawa** [comment]
imo the US system is confusing :thinking:

Anyway, might add it later. I would prefer a suggestion in MH #suggestions channel than an actual issue in this case

**Comment by Kodehawa** [comment]
also 25/01/1999 is valid too for example
