### ISSUE TITLE
[ Bug ] ~>birthday month 2 problem

### ISSUE THREAD

**Issue by joameba** [Mantaro/MantaroBot#242]
If you want to know february birthdays you get March's instead
I found this thread solved in october but the problem persists
![screenshot_63](https://user-images.githubusercontent.com/47150050/51920074-6d3fbf80-23c3-11e9-8110-a4d8ea52d3c0.png)

**Comment by Kodehawa** [comment]
this is a very clap bug

I'll fix it on a few

**Comment by MrLar** [comment]
This has been fixed
