### ISSUE TITLE
[ Bug ] Profile stats last daily error

### ISSUE THREAD

**Issue by allanf181** [Mantaro/MantaroBot#252]
**Describe the bug**
Profile stats last daily error

**To Reproduce**
Steps to reproduce this behavior (if applicable):
->profile stats

**Expected behavior**
I'm sure this date is wrong.

**Additional context**
![image](https://user-images.githubusercontent.com/14101716/52991070-daa2a700-33e9-11e9-8cbe-40ce5c87caed.png)

**Comment by Kodehawa** [comment]
that happens when you haven't ever claimed dailies I think or the value resets to 0. Oops.
