### ISSUE TITLE
[ Feature Req. ] A CC modifier (like -nsfw) to automatically remove the command-invoking message.

### ISSUE THREAD

**Issue by konradsmolko** [Mantaro/MantaroBot#259]
**Describe what you would like us to add**
An option for a custom command to automatically remove the message that invoked it.

**Additional context**
Using custom commands to help moderate channels helps a lot, but creates unwanted clutter in the form of the invoking message.

As much as the moderator could delete their own message, it does add overhead in high-traffic situations and lowers readability of the channel.

**Comment by Kodehawa** [comment]
Any context you think this would be useful in?
