### ISSUE TITLE
[ Question ] About fishing bait

### ISSUE THREAD

**Issue by juuzour** [Mantaro/MantaroBot#260]
Like a topic, how to use fishing bait?
and how increase lvl in my profile ?

**Comment by MrLar** [comment]
You level increases as you talk in servers, you gain about 1-8 EXP per messages, however there is a cooldown of 30 seconds between messages being counted to discourage spamming. And you can use bait with `~>useitem bait` and even multiple with `~>useitem bait -amount X` where X is a number between 1 and 9.
