### ISSUE TITLE
[ Bug ] Can’t use the diamond pickaxe in ~>mine

### ISSUE THREAD

**Issue by Joe23p4** [Mantaro/MantaroBot#268]
**Describe the bug**
When using the ~>mine function, it errs and tells me that I have no pickaxe to mine with, even when I use ~>mine "diamond pickaxe", it simply won’t work

**To Reproduce**

**Expected behavior**
I expected it to function properly or at least the error message providing detailed steps on how to use the function.

**Additional context**

**Comment by Kodehawa** [comment]
without quotes on mine
