### ISSUE TITLE
[ Feature Req. ] e926 image command

### ISSUE THREAD

**Issue by Isvvc** [Mantaro/MantaroBot#275]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Double checked existing Issues/Pull Requests for a similar feature.

**Describe what you would like us to add**
Add an image bot for e926 that works the same as the e621 bot but without requiring an NSFW channel.

**Additional context**
There's currently an e621 bot for posting images from e621. e926 is an entirely SFW mirror of e621 and thus could be used safely in SFW channels.

**Comment by Kodehawa** [comment]
Please also create an issue on https://github.com/Kodehawa/imageboard-api to create a default binding for that imageboard. We'll go along with it later this month.

Thanks~

**Comment by Kodehawa** [comment]
Issue will be followed on https://github.com/Kodehawa/imageboard-api/issues/20

**Comment by Kodehawa** [comment]
Since this has been added to imageboard-api, am reopening this. Are you 100% sure this won't post any NSFW stuff?

**Comment by Isvvc** [comment]
The point of the site is to be SFW, but I haven't been able to find specific documentation of how they define "safe" posts or what the moderation is like, so no, I'm not 100% sure unfortunately 🤔

**Comment by Kodehawa** [comment]
I've been watching e926 sparingly over the last year or so, to make sure the results were truly safe, and the answer is sadly no. I guess it scrapes e621 and looks for safe-tagged images, but sadly that's obviously not too accurate.

I know this is a very late reply, sorry.

If you're okay with me adding this as a command locked to NSFW channels, I'd be fine with it.
