### ISSUE TITLE
[ Bug ] sparkles found with comet pickaxe

### ISSUE THREAD

**Issue by JunisvaultCo** [Mantaro/MantaroBot#276]
**Before submitting I have:**\
Made pretty sure this is unintended. Comet pickaxe should be lower than Star Pickaxe, and according to wiki ( https://github.com/Mantaro/MantaroBot/wiki/Collectable-Items), in order for sparkles to be dropped you need higher than or equal to a Star Pickaxe. Unless the fact I probably had haste potion buff on actually has an effect into making it suddenly possible for sparkles to drop when mining with a pickaxe smaller than star pickaxe.

**Describe the bug**
According to wiki, it should be minable only with star pickaxe or higher. But I mined it with a comet pickaxe, as seen here. https://imgur.com/a/J5ucvZD

**To Reproduce**
->mine with comet pickaxe equipped and haste potion buff.

**Expected behavior**
It should have dropped anything but sparkles(and well, premium crate), at least according to wiki.

**Comment by Kodehawa** [comment]
I'll check, thanks for the report.

**Comment by Kodehawa** [comment]
This is intended as per https://github.com/Mantaro/MantaroBot/blob/master/src/main/java/net/kodehawa/mantarobot/commands/MoneyCmds.java#L912

Mining with lower picks (star/comet) has an effect on sparkles too, but the probability is lower. Moving issue to wiki mantainer @MrLar

**Comment by MrLar** [comment]
Has been reflected on the wiki.
