### ISSUE TITLE
[ Bug ] Can't cast star pick

### ISSUE THREAD

**Issue by lostyouo** [Mantaro/MantaroBot#279]
I have 2 star gem and a pick for casting star pick.
I've type: ~>cast "star p" but it said  =You don't have the necessary item Star Gem to proceed with this cast

9:44am i checked inv:

![rene2](https://user-images.githubusercontent.com/46774132/63480222-ace70980-c4c3-11e9-91bf-f2fb3bbe13a2.png)

9:45am i try casting, but it doesnt work
![rene1](https://user-images.githubusercontent.com/46774132/63480276-d011b900-c4c3-11e9-9394-d5035336d36e.png)

Please fix this, thank you

**Comment by MrLar** [comment]
Double check that the item with the Star emote is actually Star Gem, chances are what you are actually looking at is the Price item. You can double check by using `~>inventory -info`.

**Comment by MrLar** [comment]
Also, next time please don't remove all of the template you receive when choosing "Bug Report" and actually fill the template the way we want you to.

**Comment by lostyouo** [comment]
Alright, thank you. Sorry about that.

**Comment by Kodehawa** [comment]
Any follow-up?
