### ISSUE TITLE
[ Bug ] Game of Guessing pokémon

### ISSUE THREAD

**Issue by Nylezer** [Mantaro/MantaroBot#280]
Whenever we play ->game pokemon and it gives us a Kanto pokémon as a guess, it shows us this:
http://tinypic.com/images/goodbye.jpg

This ONLY happens when the pokémon to guess is from Kanto! Maybe the silhouettes are slowly getting outdated and need to be refreshed?

Thank you

**Comment by MrLar** [comment]
This is an issue with the fact that tinypic has been shutdown, rendering all images uploaded to there unusable. An issue we are very aware of but cannot fix over night. This may take a while to be fixed.

**Comment by Kodehawa** [comment]
This has been fixed on the MAPI level, so we all good now.

RIP Tinypic, though.
