### ISSUE TITLE
[ Question ] >trivia isnt a valid command?

### ISSUE THREAD

**Issue by fieldofgreen** [Mantaro/MantaroBot#281]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [ ] Read the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) to make sure my question is not answered there.
- [ ] Checked `~>help <command name>` (if this is command related) to make sure my question is not answered there

**Question:**
Curious as to why ~>trivia isnt in ~>game, I noticed it was outside of game in it's own category but then why does ~>game multiple trivia 5 work?
It is also referenced in the ~>help game but cannot be played as a single game unless used as just ~>trivia
I may have just missed some long old problem posted here before but I searched it and didnt find one.

**Comment by Kodehawa** [comment]
The technical answer for that can be found by reading the https://github.com/Mantaro/MantaroBot/blob/master/src/main/java/net/kodehawa/mantarobot/commands/GameCmds.java source.

**Comment by fieldofgreen** [comment]
Ah ok cool thanks. Makes more sense to have trivia be it's own method to call inside of game when its needed.
