### ISSUE TITLE
[ Bug ] ~>profile timezone Europe/London is invalid

### ISSUE THREAD

**Issue by freyjadomville** [Mantaro/MantaroBot#287]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Given the documentation/command reference says that Europe/Berlin is a valid argument to ~>profile timezone, one would reasonably expect "Europe/London" to be a valid argument. However, because of how the validation is done it is not possible for that argument to be entered whilst the UK is not in daylight saving time, as the GMT value that is default will match the returned ID from the call to .getID() inside Utils.isValidTimezone. I'll be submitting a PR for this this evening, as I think I know how to fix this.

**To Reproduce**
Steps to reproduce this behavior (if applicable):
Use the command '~>profile timezone Europe/London'

**Expected behavior**
Timezone should be set to the location version of GMT/GMT+1 adjusting for daylight savings.

**Comment by Kodehawa** [comment]
This seems indeed broken.

**Comment by Kodehawa** [comment]
Fixed. Forgot about putting the bug on the commit message(s).

Haven't released it yet. Will be in-track for 5.6.0.
