### ISSUE TITLE
Gamble glitch

### ISSUE THREAD

**Issue by lettuce-kink** [Mantaro/MantaroBot#289]
![Screenshot 2019-12-23 at 4 18 55 AM](https://user-images.githubusercontent.com/59164579/71349122-307d3980-253c-11ea-858e-f93abd56283d.png)
i keep messing up on the thing and i noticed that the bot seems to think that i gambled? its not a big deal but its a waste of time aha

**Comment by Kodehawa** [comment]
Thanks. Will see if I can make this behavior better.

**Comment by Kodehawa** [comment]
Fixed in 391518ae21bc2b9d8fc239116c38c1f5ed70114b
