### ISSUE TITLE
Loot time cooldown increasing

### ISSUE THREAD

**Issue by Deveritus** [Mantaro/MantaroBot#29]
Not so much for me, but the cooldown on the loot command is continuously going up for someone on my server and there's no clear reason why. At this point in time, the cooldown has reached almost eight hours. This has gone up from the timer stating they need to wait six hours, since I was first made aware of the issue. 
![screenshot_14](https://cloud.githubusercontent.com/assets/29121486/26679361/b6889734-46a2-11e7-98c9-fc60e7ff592e.jpg)

Every so often, whenever the person checks to see if the time is going down, it scales up further. I've already advised them to try waiting until the seven-hour timer is cleared, however I still have no idea what's even wrong with this. I've also already tried removing Mantaro and re-adding the bot, however that did not resolve the issue.

**Comment by MrLar** [comment]
Was fixed in the reboot that happened about an hour ago :).

**Comment by MrLar** [comment]
To further explain this basically the server had some issues which made ratelimits fail and increase after they shoudve been cleared. But its all good now.
