### ISSUE TITLE
Broken star pick diapered 

### ISSUE THREAD

**Issue by Little-Magician** [Mantaro/MantaroBot#290]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Replace this text with a clear description of the bug you are reporting.

I @Little Magician#9340 casted a star pick and I gave it to @DreamPwner#8333 but after a while of using it broke and didn't go to his inventory.

**To Reproduce**
Steps to reproduce this behavior (if applicable):
1. I had the 2 star gems already casted but I thought it was 3 star gems so I casted another but I was missing the cookie so I bought casted the star gem.
2. Finally casted the star pick. I casted everything with my comet wrench.
3. Transferred the star pick to my friend
4. He used it with energy beverage so it won't break but when it broke it just got treated like a brom's pick and didn't have the heart either so it didn't go back to his inventory.
**Expected behavior**
A clear description of what you expected to 
happen.

Would you guys please put a broken star pick on my friend's inventory.

**Additional context**
Add any other context here or remove this section entirely.
![Screenshot_20191231-102011](https://user-images.githubusercontent.com/55811361/71628958-0ec52780-2bb8-11ea-9ce5-c58bebb66146.png)
![Screenshot_20191231-102011](https://user-images.githubusercontent.com/55811361/71629008-4207b680-2bb8-11ea-86cc-8a44bdcd7fe3.png)

**Comment by MrLar** [comment]
This is intended behavior. An tool that breaks does not drop a broken version 100% of the time. It has a *chance* to drop it.
