### ISSUE TITLE
pokemon game basculin silhouette is broken

### ISSUE THREAD

**Issue by Little-Magician** [Mantaro/MantaroBot#292]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Replace this text with a clear description of the bug you are reporting.

**To Reproduce**
Steps to reproduce this behavior (if applicable):

**Expected behavior**
A clear description of what you expected to happen.

**Additional context**
Add any other context here or remove this section entirely.
![image](https://user-images.githubusercontent.com/55811361/71760760-eb340280-2e7f-11ea-8e3f-e062c6eb4b0c.png)

**Comment by Kodehawa** [comment]
That's some amusing bug.
I honestly still have no idea of why it happens. Mind giving me the image url? (right click, copy image url)

**Comment by Little-Magician** [comment]
https://apiv2.mantaro.site/image/pokemon/6a421c7823161277968f17f8925c5649e1e5170e890babfafaed536451dbcb14.jpg

**Comment by Little-Magician** [comment]
https://apiv2.mantaro.site/image/pokemon/6a421c7823161277968f17f8925c5649e1e5170e890babfafaed536451dbcb14.jpg

**Comment by Kodehawa** [comment]
Is this still the case? Haven't heard of it in a while.

**Comment by Little-Magician** [comment]
I don't know I have not been playing mantaro for a while now

**Comment by Kodehawa** [comment]
Haven't seen reports of this in months, closing.
