### ISSUE TITLE
[ birthday ] the bot no longer updates given or removed birthdays

### ISSUE THREAD

**Issue by randomedits** [Mantaro/MantaroBot#300]
**Before submitting I have
![brokenbot](https://user-images.githubusercontent.com/62448030/77206705-f89b7900-6acd-11ea-94bc-ac068d50a479.PNG)
![brokenbot](https://user-images.githubusercontent.com/62448030/77206714-ffc28700-6acd-11ea-9428-dcc892e8f669.PNG)

:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [ ] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Replace this text with a clear description of the bug you are reporting.

**To Reproduce**
Steps to reproduce this behavior (if applicable):

**Expected behavior**
A clear description of what you expected to happen.

**Additional context**
Add any other context here or remove this section entirely.

**Comment by MrLar** [comment]
This is intended behaviour, it takes 23 hours for that list to update for technical reasons. Altho honestly @Kodehawa you might wanna start including a note on that command that mentions that.

**Comment by randomedits** [comment]
I broke the bot :(

**Comment by randomedits** [comment]
Are we sure it's intended to do that? It wasn't doing this yesterday.

**Comment by MrLar** [comment]
It is very much intended

**Comment by randomedits** [comment]
Okay that makes sense, thankk youu :)
