### ISSUE TITLE
[ Bug ] The bot leaves the voice channel after playing one song 

### ISSUE THREAD

**Issue by dot923** [Mantaro/MantaroBot#305]
The bot leaves the vc after playing one song 
After putting my playlist the bot still keeps the leaving the voice channel

**Comment by Kodehawa** [comment]
Should be fixed. Not really sure so I'll keep it open.

**Comment by hayabuza48** [comment]
I got error with codes (Maybe we threw it there? Just in case, the error id is Ca7sh+QAAGQ) How to fix this?
