### ISSUE TITLE
[ Bug ] Put a short description of the bug here (leave the leading brackets and the text in it)

### ISSUE THREAD

**Issue by CharlittGurl** [Mantaro/MantaroBot#306]
Hello, so i dont know that this is a bug or something else...

Im trying to set the birthdays but i correctly set the channel name
in the but it says "Cannot find any text channel with that name :(".
I dont know what im doing wrong... 

-CharlittGurl

**Comment by Kodehawa** [comment]
We need more information. Also please contact us on support.mantaro.site and post about it on #support. 

If the channel contains emojis or special characters, try removing them before using the command.
