### ISSUE TITLE
[ Question ] Replace this with a short description of your question (leave the leading brackets and the text in it)

### ISSUE THREAD

**Issue by pandora2cool** [Mantaro/MantaroBot#307]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [ ] Read the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) to make sure my question is not answered there.
- [ ] Checked `~>help <command name>` (if this is command related) to make sure my question is not answered there

**Question:**
So I claimed people in this one server to be my waifu and now they left the server. Do you know how to unclaim them when they leave the server?

**Comment by Kodehawa** [comment]
Do `~>waifu -id` then `~>waifu unclaim <id here> -unknown`. Do not include the <>
