### ISSUE TITLE
[ Bug ] Daily issue with auto tag

### ISSUE THREAD

**Issue by Aicchan** [Mantaro/MantaroBot#312]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x ] Made sure this is actual unintended behaviour.
- [x ] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [ ] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

When I claimed my daily, I by mistake tapped on my name tag and  sent the request. So it showed up that I couldnt give the daily to myself. Because for the day I already used the ->daily command i couldn't claim it again until net day and i lost my 385 days in a row :(

It went like this:
I said: ->daily @Aicchan#5849
Mantaro:  Use daily without mentioning yourself if you're gonna mention yourself :P
I repeated command "daily"
Mantaro: :stopwatch: Y-You're calling me so fast that I'm getting dizzy... (Ratelimited)
 You'll be able to use this command again in 23 hours, 59 minutes and 51 seconds.

Next day I lost the streak.

**Expected behavior**
For the bot to understand that it was an auto tag and give me the daily.

I'm sorry if its weird to understand, its my first form.

**Comment by Kodehawa** [comment]
Oh. Thanks for the report.

**Comment by Kodehawa** [comment]
Fixed by https://github.com/Mantaro/MantaroBot/commit/60547671ccab1d1588f28cd857a6ea9f2105c54b
