### ISSUE TITLE
[ Bug ] Mantaro needlessly requires global "embed links" permission

### ISSUE THREAD

**Issue by RasmusAntons** [Mantaro/MantaroBot#329]
**Before submitting I have:**
- [ ] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [ ] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Up until now, Mantaro only required the "Embed Links" permission for the channel the command was sent in, since commit [06ae9b0](https://github.com/Mantaro/MantaroBot/commit/06ae9b076a868c45f082778e79e684e86c4b3a62) it requires the guild-wide permission.

**To Reproduce**
Remove Mantaro's global permission to embed links, give it the permission in one channel and execute a command in that channel.

**Expected behavior**
The command should execute normally as before.

**Additional context**
On our discord, we have restricted all bots to a subset of channels and removed their reading permissions by default. Giving it the global permission to embed links isn't a huge issue but it doesn't seem necessary.

**Comment by Kodehawa** [comment]
Will be fixed on next release, probably tomorrow.
