### ISSUE TITLE
[ Feature Req./Suggestion ] Being able to delete the author message in a custom command

### ISSUE THREAD

**Issue by AlejandroTLOZ** [Mantaro/MantaroBot#331]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Double checked existing Issues/Pull Requests for a similar feature.

**Describe what you would like us to add**
I would like to create a command like a "say" command but the author message get deleted, leaving only what mantaro said.

**Comment by Kodehawa** [comment]
Too abusable.
