### ISSUE TITLE
"->osustats" command not working

### ISSUE THREAD

**Issue by jamalObama** [Mantaro/MantaroBot#332]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Replace this text with a clear description of the bug you are reporting.

**To Reproduce**
Steps to reproduce this behavior (if applicable):

**Expected behavior**
A clear description of what you expected to happen.

**Additional context**
Add any other context here or remove this section entirely.

**Comment by Haxiz** [comment]
The osustats command was removed since update 5.5.5
