### ISSUE TITLE
[ Bug ] Year numbers on birthdays are missing

### ISSUE THREAD

**Issue by cherry25565** [Mantaro/MantaroBot#336]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Made sure this is actual unintended behaviour.
- [X] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [X] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
The year numbers on the birthday dates are missing.

**To Reproduce**
Use the `birthday month X` command
The response shows up like this:
`+ Name          : 01-03`

**Expected behavior**
The expected response would be this:
`+ Name          : 01-03-2010`

**Additional context**
I don't know if this is a wanted change but this definitely was changed in the past few days.

**Comment by MrLar** [comment]
Not a bug, we have recently removed years from birthdays for various legal reason as well as they didn't show on profiles to begin with so they should not anywhere else.
