### ISSUE TITLE
[ Bug ] Birthday list doesn't update with new birthdays.

### ISSUE THREAD

**Issue by Erebus-Mecha** [Mantaro/MantaroBot#339]
**Before submitting I have:**\
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
I'd set my birthday for the bot a long time ago. I added it to another server, and the members were setting their birthdays with it. But when the birthday list command was tried, it only showed mine. It's still been that way currently.

**To Reproduce**
Have another person set their birthday, then type "~>birthday list". Theirs doesn't show.

**Expected behavior**
That it would've shown, of course.

**Additional context**
<img width="463" alt="Oof" src="https://user-images.githubusercontent.com/69965507/90759477-61cf2480-e2d8-11ea-90eb-cbe2b5b4bd44.PNG">

**Comment by MrLar** [comment]
Newly set birthdays do not show until 23 hours have passed due to technical and spam prevention reasons

**Comment by Erebus-Mecha** [comment]
> Newly set birthdays do not show until 23 hours have passed due to technical and spam prevention reasons

Got it, thanks for informing.
