### ISSUE TITLE
Dosent play music.

### ISSUE THREAD

**Issue by HasanBrandsXD** [Mantaro/MantaroBot#34]
Sometimes Mantaro dosent even play music.
Or sometimes when it does it plays very blur, like, I cant even hear it. At that moment, I checked the ping. The ping was 2994 ms >.<

**Comment by Kodehawa** [comment]
Probably host issues. We're moving in 2 days to a better host since the current one gives problems

**Comment by HasanBrandsXD** [comment]
Okay, then. You can close this issue now.
