### ISSUE TITLE
[ Bug ] action commands not working

### ISSUE THREAD

**Issue by Boundarybreaker** [Mantaro/MantaroBot#341]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Action commands are returning errors

**To Reproduce**
Steps to reproduce this behavior (if applicable):
- use any action command (tested: kiss, hug, cuddle, lewd)

**Expected behavior**
The action command should respond with a gif of the specified action, instead of an error message

**Additional context**
Add any other context here or remove this section entirely.
Error IDs:
- CmHfqbPEAAo
- CmHf3BpCAEg
- CmHf6ODEAIw
- CmHgBw+AADI
- CmHgFRRAAEg
- CmHgIC+CADI
- CmHgU4TAAD0

**Comment by MrLar** [comment]
more than likely a third party issue with the API we use, things should have returned to normal by now. They probably had a hiccup,
