### ISSUE TITLE
[ Bug ] `profile timezone` example is not working

### ISSUE THREAD

**Issue by alkatar21** [Mantaro/MantaroBot#343]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
`~>profile timezone Europe/Berlin` that is mentioned in the documentation https://github.com/Mantaro/MantaroBot/wiki/Command-reference-and-documentation#currency-commands in point 6.3 is not working as expected.

**To Reproduce**
Steps to reproduce this behavior (if applicable):
![grafik](https://user-images.githubusercontent.com/61387986/92700542-38da0680-f34f-11ea-8d7b-aa487b2111e7.png)

**Expected behavior**
To set the timezone to Europe/Berlin.

**Comment by Kodehawa** [comment]
Fixed. Forgot about putting the bug on the commit message(s).
