### ISSUE TITLE
[ Docs/Wiki ] "Currency 101" not updated to new birthday format

### ISSUE THREAD

**Issue by Ravendwyr** [Mantaro/MantaroBot#346]
**Before submitting I have**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] (In case of a missing documentation) Made sure this is not a recently added feature.
- [X] Made sure this feature is not intentionally undocumented (like collectable items missing).
- [X] Searched the entirety of the wiki for it, to make sure it is not documented in another section

**Describe what you think is wrong with the Documentation**
Good morning,

I was browsing through the wiki earlier to see what features Mantaro had that I may not have been aware of (specifically, wondering if it had a starboard-like feature) and noticed the "Currency 101" page still lists the birthday command as `~>birthday dd/mm/yyyy`. I had already set a birthday using the `~>birthday dd-mm` format as shown in other wiki pages and thought I could add my birth year as well, however Mantaro quickly told me the dd/mm/yyyy format was no longer supported and that dd-mm should be used instead.

I appreciate that this is a minor issue, however it may not hurt to update the "Currency 101" page to prevent confusion for others.

I hope you are all staying safe and well in these uncertain times. 😃

**Comment by Ravendwyr** [comment]
I just noticed the "FAQ" page also has the old "dd-mm-yyyy" format. That page might need some tweaks as well. 😃

**Comment by Haxiz** [comment]
Fixed
