### ISSUE TITLE
[ Bug ] birthday list error

### ISSUE THREAD

**Issue by charlottehohoho** [Mantaro/MantaroBot#349]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
The command `->birthday list ` doesn’t list all users’ birthdays. 

![DEA52C03-432F-4F23-AAE2-563F33C83A41](https://user-images.githubusercontent.com/55075756/94550333-22f09f00-0286-11eb-9a0b-befbaa761125.jpeg)

**Expected behavior**
I expected the command to list all users’ birthdays.

**Comment by charlottehohoho** [comment]
The birthday of this user also doesn’t appear. 

![22876FA8-0FE3-47FC-A72C-3A4D36A641C8](https://user-images.githubusercontent.com/55075756/94550859-0c971300-0287-11eb-8f3b-776222f2f60b.jpeg)

**Comment by MrLar** [comment]
it takes 24 hours before new birthdays are considered "ready", aka are cached and wont be an issue spam vise, they only show after that period

**Comment by charlottehohoho** [comment]
Notice the dates tho, the second screenshot’s user set their bday on 27/9
🤔 isn’t it over 24hrs already?

**Comment by MrLar** [comment]
the latter person has probably not run allowserver yet

**Comment by charlottehohoho** [comment]
Oic, thanks! :)
