### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Teremok333** [Mantaro/MantaroBot#355]
I can not create a fishing rod although I have everything and a level 2 key
![Screenshot_2020-10-15-12-07-46-248_com discord](https://user-images.githubusercontent.com/72915975/96103422-5c5d1780-0ee0-11eb-9e59-a8dcdba279a0.jpg)

**Comment by MrLar** [comment]
You have to specify which wrench to use otherwise it will use the default which is too low of a level for this cast.
