### ISSUE TITLE
Badge Bug

### ISSUE THREAD

**Issue by carameals** [Mantaro/MantaroBot#359]
![Screenshot_20201030-073502_Discord](https://user-images.githubusercontent.com/73700780/97705904-cfd75b00-1a82-11eb-9bc3-fc3fc6a9ff45.jpg)
![Screenshot_20201030-073457_Discord](https://user-images.githubusercontent.com/73700780/97705913-d4037880-1a82-11eb-87ea-0a8f5e74a031.jpg)
I am not sure this is where I should post my concern, but I am attempting to go badge hunting. At first I thought maybe it would take a little to load my trophy after I achieved 40 crates to open, but I didn't receive the trophy. I apologize if this is a common issue, but I just wanted to let you know about it.

**Comment by MrLar** [comment]
Not a bug, you have to run profile first for almost every badge to be registered.

**Comment by carameals** [comment]
I've done that multiple times since I've got it to 40 and still no change
happened. I've been past 40 for about a month or two now.

**Comment by MrLar** [comment]
do note that running `profile stats` won't make it register only profile without any sub command
