### ISSUE TITLE
[ Bug ] spelling mistake in the mmgame pokemon command

### ISSUE THREAD

**Issue by Tleil** [Mantaro/MantaroBot#361]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
With the mmgame pokemon command, if Gossifleur is shown it doesn't accept that spelling, instead needing Gosifleur, which is incorrect.
**To Reproduce**
Spell the name correctly.

**Expected behavior**
winning 85 credits? hahaha

**Comment by Kodehawa** [comment]
Thanks. I'll fix it on the API in a few (aka whenever we reboot it)

**Comment by Kodehawa** [comment]
I fixed it internally. I'll push a new API version in a few days probably. Aware of any other misspells?

**Comment by Tleil** [comment]
Ah, sorry for the delayed reply.  Not that I can think of, apart from some
of the base forms requiring you to specify it, which is a tad annoying but
inconsequential.

**Comment by Kodehawa** [comment]
pushed fix
