### ISSUE TITLE
Second input for trivia always marked incorrect

### ISSUE THREAD

**Issue by thetwodude** [Mantaro/MantaroBot#37]
Mantaro usually says you're correct if you input the answer in the first time, but if you guess the answer a second time, Mantaro always says it's wrong. 

example:
![image](https://user-images.githubusercontent.com/29446934/27165050-609c88c2-5146-11e7-8bd8-05183df00fdf.png)

This happens every single time you answer a second time.

**Comment by Kodehawa** [comment]
Should be fixed in next version.
