### ISSUE TITLE
game command is glitched

### ISSUE THREAD

**Issue by leiia** [Mantaro/MantaroBot#38]
so, basically, this is almost the same problem that's stated in issues #19 and #23. the game command is glitched and it won't let me answer or end the current game, nor will it timeout. i've tried using `~>opts lobby reset` a couple of times, but it resets and glitches again shortly after. any ideas?

p.s. here's a [screenshot](https://i.gyazo.com/78c73d0dc6e5acff853f7af7bfcff3ba.png) if you need a visual. thank you!

**Comment by Kodehawa** [comment]
There is currently a problem in Interactive Operations where the marry command would run for basically infinite time. This has been fixed by commit https://github.com/Mantaro/MantaroBot/commit/81b079ccf1c2cc41e53ed0ef73c7440ffbb95fbf but it's still not live.

**Comment by luvbeetle** [comment]
why does marry command no longer work?

**Comment by Kodehawa** [comment]
Should be fixed now.
