### ISSUE TITLE
[ Bug ] Love command marking an other user as marriage partner and giving him a 100% (Easy fix)

### ISSUE THREAD

**Issue by IxPrumxI** [Mantaro/MantaroBot#389]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Made sure this is actual unintended behaviour.
- [X] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [X] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
When using the command love and mentioning your marriage partner first then someone else the percent will be 100%.

**To Reproduce**
Marry someone, then use the command love and mention him and another user.

**Expected behavior**
The percent shouldn't change to 100%.
This can be fixed by changing src/main/java/net/kodehawa/mantarobot/commands/FunCmds.java line 257 to `if (marriage != null && mentioned.size() == 1) {`

**Comment by Kodehawa** [comment]
oops
