### ISSUE TITLE
Lock a Role from using the bot

### ISSUE THREAD

**Issue by KappaDarius** [Mantaro/MantaroBot#39]
Hey! I would like to ask if someone could tell me how I can lock or disable a role in my server to use the bot and use the bot for music or something like that !

**Comment by Kodehawa** [comment]
It's planned.

**Comment by fuyukikoneko** [comment]
Hi~
Many commands like adding roles to ~>iam require the user to be Admin.
Even though I am an Admin and server owner, they don't work and automatically show that the Permission required is Admin in order to use them.

Is there a bug that needs to be fixed on these commands?

**Comment by MrLar** [comment]
How are you using the command and what are your Permissions?

**Comment by fuyukikoneko** [comment]
Hey again!
The mistake I did was that your command ~>iam works only with one word roles (no spaces)
Can you please make it so that it can work with roles that have many words divided by space?
Like

**Comment by MrLar** [comment]
you can use spaced names by quotating them
"role name with spaces"

**Comment by fuyukikoneko** [comment]
thank you!
