### ISSUE TITLE
[ Feature Req./Suggestion ] Spotify support

### ISSUE THREAD

**Issue by Ved-s** [Mantaro/MantaroBot#392]
**Before submitting I have**\
Tested that mantaro cannot play audio from Spotify by track link

**Describe what you would like us to add**
Add Mantaro an ability to stream music from Spotify

**Comment by MrLar** [comment]
You were meant to actually change the title lol.

Just for clarification: Due quite hefty legal restrictions on spotifies end we will never truly be able to support spotify. The only way to support this is by finding the best match on youtube (which is what all the other bots do).
Additionally I do believe this is planned more or less (cc @Kodehawa)


Context: Streaming a spotify song outside of spotify is illegal and can cause heavy heavy fines.

**Comment by Ved-s** [comment]
Ok. Sad( But thanks for the explanation
