### ISSUE TITLE
Bot responds to channels without permissions

### ISSUE THREAD

**Issue by MunkyMagick** [Mantaro/MantaroBot#40]
I have removed **all** permissions for the bots group the in all but two channels(one of which was originally #general) yet it still responds to commands in those channels for which it does not have read permission, or any other permission. The bot does not have administrator permissions in it's own group.

**Comment by MunkyMagick** [comment]
Sorry, layer 8 issue...

**Comment by Kodehawa** [comment]
pat

**Comment by Sanduhr32** [comment]
*pats Kode*

**Comment by natanbc** [comment]
pls
