### ISSUE TITLE
[ Question ] How to unclaim a deleted user?

### ISSUE THREAD

**Issue by xJuul** [Mantaro/MantaroBot#403]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [ ] Made sure this is actual unintended behaviour.
- [x] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [x] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Replace this text with a clear description of the bug you are reporting.

**To Reproduce**
Steps to reproduce this behavior (if applicable):

**Expected behavior**
A clear description of what you expected to happen.

**Additional context**
Add any other context here or remove this section entirely.

**Comment by xJuul** [comment]
So i can't unclaim a deleted user even though I did what the bot said and then it says "you haven't claimed this waifu" when i did. Fix it pls ty! :)

**Comment by MrLar** [comment]
[FAQ # 10](https://github.com/Mantaro/MantaroBot/wiki/FAQ#10--can-i-unclaim-people-who-i-no-longer-share-a-server-with-or-that-show-as-unknown-user-waifu-command) answers your question. Please note that an ID is NOT username#numbers, an ID is only numbers, the FAQ also covers how to get that. Also please fill out the actual template next time.
