### ISSUE TITLE
[ Question ] How do I set the timezone on Mantaro?

### ISSUE THREAD

**Issue by jisvng** [Mantaro/MantaroBot#414]
What command do I run to set my timezone on my Mantaro profile? When I run `->time @jisvng`, it replies with "The user you mentioned has no timezone set on their profile."

**Comment by Haxiz** [comment]
~>profile timezone {your timezone here}
Search in https://en.wikipedia.org/wiki/List_of_tz_database_time_zones if you don't know what your timezone is.
