### ISSUE TITLE
Ability to divorce?

### ISSUE THREAD

**Issue by cedric248** [Mantaro/MantaroBot#44]
I want to be able to divorce someone using mantaro.

**Comment by HasanBrandsXD** [comment]
That's simple. Just type `~>marry divorce` to divorce someone that you've married.

**Comment by luvbeetle** [comment]
Why is bot down again?  it was down yesterday too?

**Comment by Kodehawa** [comment]
why is my manataro down?

anyway for those kind of questions please just refer to MH.

Also mantaro hasn't been down for the past day.
