### ISSUE TITLE
[ Question ] custom commands not showing the gif

### ISSUE THREAD

**Issue by HolyFang** [Mantaro/MantaroBot#440]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x ] Read the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) to make sure my question is not answered there.
- [x ] Checked `~>help <command name>` (if this is command related) to make sure my question is not answered there

**Question:**
I've been trying to set up a command similar to the slap, kiss or hug commands. This is the command i created as a test: ->custom new E embed:image:"https://media.giphy.com/media/eiw5mph3qBvdiiHxMa/giphy.gif%22", description:":speech_balloon: $(event.message) has punched $(event.author.mention)",color: "red"

the problem is when i type in ->E the gif never loads. How do i fix this?

**Comment by MrLar** [comment]
The image for an embed has to be a direct link to the gif. Giphy does not provide direct image URLs that only include the image, so you will have to find a different service (Example of how a direct image would, look: https://cdn.discordapp.com/avatars/302810118335102976/88bc9d0aa3e196aba1fa4403956027ae.png).
