### ISSUE TITLE
"Choose" command no longer exists?

### ISSUE THREAD

**Issue by WolfenOmega** [Mantaro/MantaroBot#455]
Is this no longer a feature, or is it just not working? It isn't working in any server for multiple people that have tried. I try "!!help choose" and it says "A command with this name doesn't exist"

From wiki:
~>choose <"option 1"> <"option 2"> {"option 3"} {"option 4"}.....

**Comment by Haxiz** [comment]
The choose command was removed last update, i just forgot to remove it from the wiki
