### ISSUE TITLE
Mention modifiers

### ISSUE THREAD

**Issue by MorseGuy** [Mantaro/MantaroBot#46]
Hey, you could add mention modifiers 
Example:
->custom new check @if{$(event.message.raw);equals;$(event.mention);User exists;User does not exist.} 
In this example, it would be required to mention a real user If you want the command returns "User exists".
Adding this modifiers,we could create commands where It would be necessary to mention someone, not just write a random word or name.
You could make something like $(event.author),with status,game,avatar,id,discriminator,name and username.

**Comment by Kodehawa** [comment]
That exists...
https://github.com/Mantaro/MantaroBot/wiki/Custom-Command-Modifiers

**Comment by MorseGuy** [comment]
I cant see it

**Comment by Kodehawa** [comment]
You mean, to get the person who gets mentioned in the message?
If that's what you mean, sure, will be added soon

**Comment by adriantodt** [comment]
Already fixed in the **stable** branch. Now Kodehawa needs to start USING **stable**.

**Comment by tkatlavendier** [comment]
Hi, I am having trouble figuring out how to mention someone else when I make a new command? I am trying to make a custom command that will mention both the person who initiated the command and the person that they tagged. For example; ~>pizza = Lavendier (author) shares a piece of pizza with Hubby (mentioned user) I have tried many different things such as (event.user.mention) but cannot get anywhere. Help :(

**Comment by natanbc** [comment]
$(event.message.raw)

**Comment by tkatlavendier** [comment]
OH THANK YOU!!!!!! <3

**Comment by MrLar** [comment]
^ There is not direct modifier for fetching mentions. Fetching the message is the closest you'll get simply use what natan sad and tag the person while running the command and it'll print it. It will also print everything else after the command name and prefix tho. To check all modifiers be sure to head to the top of the page and click wiki you'll find a documentation of every single one there.

**Comment by Kodehawa** [comment]
^ ™️

**Comment by Sanduhr32** [comment]
its easier than you expect :^)
Regex my friend

**Comment by Kodehawa** [comment]
PR it

**Comment by Sekari** [comment]
So I'm not sure if its an issue with what i wrote or not but when i use $(event.author) in the title of the embedded commands, it prints as <@!____> where ____ is a really long number which I'm assuming is my ID. it doesn't happen for anywhere other than the title though. 

also, will we ever get an rng function? o: hehe

**Comment by MrLar** [comment]
Embed titles do not support mention resolving this is a Discord limitation.

**Comment by Sekari** [comment]
oh i see thanks

**Comment by MrLar** [comment]
Mention modifiers will be a thing in Mantaro Version 4.9 as part of the Custom Command rewrite, therefore i'm closing this.

**Comment by natanbc** [comment]
Will only be available in a new type of custom commands btw
