### ISSUE TITLE
[ Bug ] Pet not working properly, only I can use it, my partner doesn't

### ISSUE THREAD

**Issue by weylonz** [Mantaro/MantaroBot#465]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Made sure this is actual unintended behaviour.
- [X] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [X] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
When I put the pet on "Marriage" none of us can use it anymore and its not shown in our profiles, only I can use it if i put it on Personal. We have a house, a car, but I am just not sure about the pethouse since its not showing in our marry status.

**To Reproduce**
Steps to reproduce this behavior (if applicable): No matter what I do, it is not working properly, someone else on the server did the same thing and it just worked perfectly fine for them, just not for us.

**Expected behavior**
I want the pet to work for both me and my partner.

**Comment by MrLar** [comment]
This is intentional behaviour. A personal pet will not convert to a marriage pet, it will stay your personal one. By choosing Marriage as your active choice you are switching the pet to the one on your marriage, since there is none, neither of you can use one. You would have to buy another pet after choosing marriage.

**Comment by weylonz** [comment]
But it wasnt even possible to buy a pet without a marriage, the pet got bought after the marriage? What did I do wrong?

**Comment by MrLar** [comment]
It used to not be possible before a certain update, now pets can be owned as an individual, and the default choice is personal, so you simply bought a personal one rather than a marriage one.

**Comment by weylonz** [comment]
Okay I understand that, but I had no choice what kind of pet it should be when buying the pet, it just automatically chose personal without letting me know.

**Comment by MrLar** [comment]
As I said, you choose marriage using pet choice marriage and *then* buy the pet.

**Comment by weylonz** [comment]
Then I suggest the bot giving people a hint before buying a pet.

**Comment by Kodehawa** [comment]
This is matters for https://support.mantaro.site btw. 

Also the bot tells you
![image](https://user-images.githubusercontent.com/20606963/112724104-5e47ef80-8ef0-11eb-91bf-dad8f8593ff0.png)
