### ISSUE TITLE
How to get other pick like diamond pick?? 

### ISSUE THREAD

**Issue by Idkss** [Mantaro/MantaroBot#473]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [x] Read the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) to make sure my question is not answered there.
- [x] Checked `~>help <command name>` (if this is command related) to make sure my question is not answered there

**Question:**
Replace this text with your question. Please be as detailed as possible so we can help you more quickly.

**Comment by Kodehawa** [comment]
Please ask such questions in the #support channel of the official server at https://support.mantaro.site

**Comment by MrLar** [comment]
Refer to `~>help cast` and `~>cast list`. We also highly suggest you join our official support server for asking generic questions as Kode already mentioned.
