### ISSUE TITLE
Birthday commands are not working

### ISSUE THREAD

**Issue by HiLordReilo** [Mantaro/MantaroBot#474]
Well, everything is on screenshot
![image](https://user-images.githubusercontent.com/68978107/114279322-b3314d00-9a3c-11eb-9fa2-299aa6b84835.png)
I tried to use commands from wiki, but it gives me the same error

**Comment by MrLar** [comment]
Please refer to our [wiki for birthdays](https://github.com/Mantaro/MantaroBot/wiki/Birthday-101) as you are simply doing it wrong and this is not a bug.

**Comment by HiLordReilo** [comment]
But I'm doing it as listed here:
_~>opts birthday enable <channel name> <role name>_
I also used !yuyu-birthday allowserver, but still get this error
what I'm doing wrong then?

**Comment by MrLar** [comment]
You did `birthday enable <channel> <role>` where as it should be the way you said with opts before birthday (`opts birthday enable <channel> <role>`)

**Comment by MrLar** [comment]
It should also be noted that given by the role you tried to provided, you likely misunderstood how this system works. The name Developer sounds like a role with admin-like permissions. However the Birthday announcer will **assign** this role to a user when it is their birthday. This role is NOT used to determine who to check. Mantaro will also explain you this in a large prompt before setting it up.

**Comment by HiLordReilo** [comment]
oh, now I see. Sorry for inconvenience
