### ISSUE TITLE
[ Question ] Selfhosting question(?)

### ISSUE THREAD

**Issue by masonafaw** [Mantaro/MantaroBot#497]
**Question:**
I don't know if you really care or not but when I do what it says to self-host gradlew gives and error with something about git.

**Comment by MrLar** [comment]
1) You are supposed to leave the issue template as is and actually fill it out and not just submit it with the unreplaced title.
2) We do not provide any help whatsoever about self-hosting the bot, as our read me states. You are going to have to find your way around solving that error yourself. Given that you didn't really provide any detail we wouldn't be able to help you annyway (not  that we would if you did like said.)
