### ISSUE TITLE
 Error compiling...

### ISSUE THREAD

**Issue by pedroricardo** [Mantaro/MantaroBot#54]
Error print:
https://media.discordapp.net/attachments/344262727461502976/344263761177214976/unknown.png

Print from debug: > gradlew build --debug --stacktrace
https://media.discordapp.net/attachments/344262727461502976/344264948005863425/unknown.png?width=1439&height=562

**Comment by Kodehawa** [comment]
change 1.0.7-rythm to 1.0.5

**Comment by pedroricardo** [comment]
Where can I do this?

**Comment by pedroricardo** [comment]
![image](https://user-images.githubusercontent.com/25847896/29201497-1c611530-7e35-11e7-8763-588bf1b1960b.png)
The error persists :(

**Comment by Kodehawa** [comment]
remove -rythm, just 1.0.5...

**Comment by pedroricardo** [comment]
Now it worked: D
Thank you very much for your attention. <3
