### ISSUE TITLE
MantaroBot Database

### ISSUE THREAD

**Issue by pedroricardo** [Mantaro/MantaroBot#55]
Which database does mantaro use? 
Which character set does the mantaro database use utf8mb4?

I set up the database and this error continues to return in the logs
![image](https://user-images.githubusercontent.com/25847896/29242130-646a7d70-7f5d-11e7-81d1-11cb7babcf40.png)

**Comment by natanbc** [comment]
Mantaro uses RethinkDB, to change the database you'd need to rewrite most of the core of the bot

**Comment by pedroricardo** [comment]
thank you
I'll set up RethinkDB here


The errors in the log and because of this?

**Comment by Kodehawa** [comment]
I would like to point out that self-hosting mantaro isn't supported for now and it is really a pain in the ass to do

**Comment by pedroricardo** [comment]
I understood Kodehawa, but could you at least tell me how I can solve this?

![image](https://user-images.githubusercontent.com/25847896/29242980-66dcb614-7f6b-11e7-98d9-076c70867ea2.png)

**Comment by natanbc** [comment]
There's nothing wrong there

**Comment by pedroricardo** [comment]
So why does not it run?
Every time I run the application, it returns me the same msg in log

**Comment by Kodehawa** [comment]
That message is not an error, neither it prevents mantaro from starting up, there must be something else on the logs

**Comment by pedroricardo** [comment]
This is really just what appears in the log :(

![image](https://user-images.githubusercontent.com/25847896/29243143-9e8a909c-7f6e-11e7-969b-3b0a589d3d67.png)

**Comment by Kodehawa** [comment]
No idea at all, works just fine here.
