### ISSUE TITLE
!transfer command

### ISSUE THREAD

**Issue by groovyNY** [Mantaro/MantaroBot#59]
Bot says !transfer command does not exist.

**Comment by MrLar** [comment]
Transfer has recently been disabled due to recent bug abuses if you want more information on this and future cases please join [Mantaro Hub](https://discord.gg/6xmr6YG) our support guild.

**Comment by MrLar** [comment]
The command will be back somewhere arround today tho. So no worries!

**Comment by groovyNY** [comment]
Thanx a lot, appreciate it!

**Comment by Kodehawa** [comment]
re-enabled on latest update
