### ISSUE TITLE
[ Bug ] Welcome and Leaves Messages embeds image scaling issue

### ISSUE THREAD

**Issue by ShamailNasir** [Mantaro/MantaroBot#599]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Made sure this is actual unintended behaviour.
- [X] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [X] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
Welcome and Leaves Messages embeds does not auto scale image according to the platform we use,instead the image is cropped(on android version of discord)

**To Reproduce**
Set any welcome or leave embed image

**Expected behavior**
The embedded image should have auto scaled accordingly

**On Pc**
![Screenshot (248)](https://user-images.githubusercontent.com/90579007/136687271-b7c23b60-8349-435a-adaa-910221ee94c6.png)

**On Android**
![Screenshot_20211010-115432 (2)](https://user-images.githubusercontent.com/90579007/136687333-77e8eed8-0a24-4a55-bbcd-278401b4264b.jpg)

**Comment by MrLar** [comment]
That is unfortunately nothing we can control. Embeds are entirely controlled by discord itself. You only bet is to use a smaller image.

**Comment by ShamailNasir** [comment]
> That is unfortunately nothing we can control. Embeds are entirely controlled by discord itself. You only bet is to use a smaller image.

I did try, still no good. Either the image gets too small to be seen or too large to get cropped out

**Comment by ShamailNasir** [comment]
> Thats unfortunate but we cannot really help or fix it as we do nothing to embeds it is all discord. You could report it to discord but I fear thst it is intended behavior to save resources on mobile.

Ahhh, I see. Anyways thanks for the respond.
