### ISSUE TITLE
did i do something wrong or is the use slot coin not working 

### ISSUE THREAD

**Issue by shadowRay888** [Mantaro/MantaroBot#60]
MantaroBOT - Today at 12:49 AM

Slots Command
Rolls the slot machine. Requires a default of 50 coins to roll.
Permission required
User
Considerations
You can gain a maximum of put credits * 1.76 coins from it.
You can use the -useticket argument to use a slot ticket (slightly bigger chance)
Usage
~>slots - Default one, 50 coins.
~>slots <credits> - Puts x credits on the slot machine. Max of 50000.
~>slots -usecoin - Rolls the slot machine with one slot coin.

Requested by Kirin
Kirin - Today at 12:49 AM
~>slots -usecoin
MantaroBOT - Today at 12:49 AM
:heavy_multiplication_x: That's not a number!

**Comment by Desiiii** [comment]
I believe this is a bug with how the help is shown. `~>slots -useticket` seems to work fine however, as you can see below. 

![1](https://image.prntscr.com/image/sWQLne9mRheTtWvHB2i4_A.png)

**Comment by shadowRay888** [comment]
thank u

**Comment by shadowRay888** [comment]
Thanks for the help
