### ISSUE TITLE
I think i found a bug or coding error.

### ISSUE THREAD

**Issue by shadowRay888** [Mantaro/MantaroBot#61]
The price of buying an item (for some items) is different than the price  that is showing in the market .
->market
MantaroBOT - Yesterday at 11:43 PM

🛒 Mantaro Market
Items
01.- :headphones: Headphones
02.- :hammer: Ban Hammer
03.- :boot: Kick Boot
04.- :floppy_disk: Floppy Disk
05.- :pencil: My Maths
06.- :ping_pong: Ping Racket
07.- :game_die: Loaded Die
08.- :musical_note: Forgotten Music
09.- :pencil2: Pencil
10.- :moneybag: Moneybag
11.- :pick: Brom's Pickaxe
12.- :milk: Milk
13.- :champagne: Alcohol
14.- :newspaper: Lewd Magazine
15.- :ring: Marriage Ring
16.- :love_letter: Love Letter
17.- :key: Crate Key
18.- :shirt: Clothes
19.- :gem: Diamond
20.- :dress: Wedding Dress
21.- :prayer_beads: Necklace
22.- :man_in_tuxedo: Tuxedo
23.- :athletic_shoe: Shoes
24.- :rose: Rose
25.- :chocolate_bar: Chocolate
26.- :cookie: Cookie
27.- :tickets: Slot ticket
28.- :house: House
Value (Buy/Sell)
:heavy_dollar_sign: N/A, $3
:heavy_dollar_sign: N/A, $12
:heavy_dollar_sign: N/A, $9
:heavy_dollar_sign: N/A, $9
:heavy_dollar_sign: N/A, $9
:heavy_dollar_sign: N/A, $13
:heavy_dollar_sign: N/A, $57
:heavy_dollar_sign: N/A, $11
:heavy_dollar_sign: N/A, $11
:heavy_dollar_sign: $79, $64
:heavy_dollar_sign: $59, $48
:heavy_dollar_sign: $50, $41
:heavy_dollar_sign: $45, $36
:heavy_dollar_sign: $44, $36
:heavy_dollar_sign: $59, $48
:heavy_dollar_sign: N/A, $48
:heavy_dollar_sign: $67, $54
:heavy_dollar_sign: $14, $11
:heavy_dollar_sign: $377, $308
:heavy_dollar_sign: $75, $62
:heavy_dollar_sign: $18, $15
:heavy_dollar_sign: $26, $21
:heavy_dollar_sign: $8, $7
:heavy_dollar_sign: $62, $51
:heavy_dollar_sign: $45, $36
:heavy_dollar_sign: $53, $44
:heavy_dollar_sign: $71, $58
:heavy_dollar_sign: $5500, $4500
Requested by RayRay
RayRay - Yesterday at 11:43 PM
->profile
MantaroBOT - Yesterday at 11:43 PM

💍 RayRay's Profile
Gamer :joystick:
No single thing is perfect by itself. That’s why we’re born to attract other things to make up for what we lack. I think we start walking in the right direction only after we start getting our counterparts beside us.
:dollar: Credits
$ 1236
:zap: Level
11 (Experience: 11204)
:military_medal: Reputation
20
:pouch: Inventory
:moneybag: x 1, :pick: x 2, :ring: x 2, :love_letter: x 1, :man_in_tuxedo: x 1, :milk: x 1, :newspaper: x 6, :prayer_beads: x 1, :key: x 4, :dress: x 2, :floppy_disk: x 1113, :shirt: x 1601, :house: x 1, :rose: x 2, :tickets: x 8, :headphones: x 1, :game_die: x 1, :chocolate_bar: x 1, :cookie: x 3, :champagne: x 1, :pencil2: x 26, :athletic_shoe: x 5000
:tada: Birthday
18-02
:heart: Married with
Kitsune Black rock shooter#7217
Badges
:joystick:  :wrench:

User's timezone: No timezone set. | Requested by RayRay
RayRay - Yesterday at 11:43 PM
->market buy 1 diamond
MantaroBOT - Yesterday at 11:43 PM
:ok_hand: Bought 1 :gem: successfully. You now have 893 credits.
RayRay - Yesterday at 11:43 PM
->market sell 1 diamond
MantaroBOT - Yesterday at 11:43 PM
:white_check_mark: You sold 1 Diamond and gained 309 credits!

i had 1236. 1236 - 893 = 343. so i brought the diamond for 343 instead of what it said on the list and i sold for 309 which is also different to the list. 
![image](https://user-images.githubusercontent.com/31619275/30055652-d630fb20-91cb-11e7-8008-47ca91a7082e.png)
![image](https://user-images.githubusercontent.com/31619275/30055684-ee09fd0a-91cb-11e7-9ad0-08a753038d11.png)

**Comment by Kodehawa** [comment]
Prices fluctuate. A $1 difference is "common" and shouldn't make much of a difference tho.

I'mma check this later, but this is prolly due to the included :tm: price fluctuation.
