### ISSUE TITLE
Error??

### ISSUE THREAD

**Issue by hajimemeboy** [Mantaro/MantaroBot#64]
I bought a crate key, but Manataro keeps saying I don't have a crate key when I try opening a crate. Surprisingly other members can't see the key as well in my inventory, unless they're just messing with me

**Comment by Kodehawa** [comment]
Can you provide some proof?

**Comment by hajimemeboy** [comment]
Proof that it won't work^

**Comment by natanbc** [comment]
??

**Comment by Kodehawa** [comment]
???

**Comment by MrLar** [comment]
????

**Comment by Desiiii** [comment]
¿¿¿

~~cuz i'm special~~

**Comment by Yuvira** [comment]
I think what these people are trying to say is "could you please provide a screenshot and/or some more information so we can better understand what the problem is here"

**Comment by hajimemeboy** [comment]
Okay I'll send the screenshots again;

**Comment by Desiiii** [comment]
That is proof you sent a response here... we need proof of the issue...

**Comment by Kodehawa** [comment]
There are no screenshots anywhere.

**Comment by Yuvira** [comment]
For whatever reason your screenshots don't seem to be showing up. Any chance you could upload them elsewhere (e.g. imgur) and link them?
