### ISSUE TITLE
[ Question ] Numeric Luck Badge

### ISSUE THREAD

**Issue by Kureka** [Mantaro/MantaroBot#668]
**Before submitting I have:**\
(Simply replace the space inside the brackets with an X for the things you have done)
- [X] Read the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) to make sure my question is not answered there.
- [X] Checked `~>help <command name>` (if this is command related) to make sure my question is not answered there

**Question:**
I can't find any trigger (addBadgeIfAbsent) for "NUMERIC_LUCK" badge in this repo (Badge.java / GambleCmds.java) or mantaro-api repo. Is it really possible to get this badge? If yes. is there any hint to get this badge? Thanks.

**Comment by MrLar** [comment]
It is very much impossible to get the badge after checking thourougly. This may or may not be fixed in the future. I'll leave that for kode to decide and leave this issue open for now. (Also side note: you won't find how to obtain hush badges beyond the original once which you can find if you know how to trace their deletion commit).

**Comment by Kureka** [comment]
> It is very much impossible to get the badge after checking thourougly. This may or may not be fixed in the future. I'll leave that for kode to decide and leave this issue open for now. (Also side note: you won't find how to obtain hush badges beyond the original ones which you can find if you know how to trace their deletion commit).

Yes I can trace the commits or just browse the files from branch/tags before the deletion for hush file, since I was developer too. Thanks for the advice and keep this issue open.

**Comment by Kureka** [comment]
I just do some random search in all commits being made since the first time this badge added (5 Nov 2018) : https://github.com/Mantaro/MantaroBot/commit/2c20d2bcc0c4e4093b76b72e2ea71393a88e4385

I can't find any trigger to obtain this badge since beginning, probably kode forgot to add the trigger and no one else bother to find out anyway.
