### ISSUE TITLE
[ Question ] Requesting the bot to play a Private playlist makes it... play a different one?

### ISSUE THREAD

**Issue by dawciu0001** [Mantaro/MantaroBot#672]
I've requested the bot to play a song from one of my private playlists on youtube ("Liked videos") and it started playing a custom playlist, unknown to me, of 300 videos, which made me curious. Is there any way the playlist with the same name was played from the bot's account?

**Comment by MrLar** [comment]
The bot does not technically have an account for looking up music. Chances are you either did not copy the full proper URL, or it simply found a public one with a similiar, the same playlist ID, which would be youtubes fault. Also please keep and fill out the actual template next time.
