### ISSUE TITLE
The Married Command is Bugged

### ISSUE THREAD

**Issue by Xcellorator** [Mantaro/MantaroBot#68]
If you're not "married" and you ask someone who is married, the person receiving the question will get the option to say yes or no. However, if you are married and you ask someone else, regardless if they are married or not, Mantaro will say that the user is already married.

**Comment by Kodehawa** [comment]
https://mantaro.ratelimited.today/2cba48.png
and some other stuff, should be fixed in next update ^^

**Comment by Xcellorator** [comment]
alright thanks :)
