### ISSUE TITLE
[ Bug ] Gelbooru command no longer works

### ISSUE THREAD

**Issue by gemdude46** [Mantaro/MantaroBot#682]
**Before submitting I have:**\
- [X] Double checked the [FAQ](https://github.com/Mantaro/MantaroBot/wiki/FAQ) for potential misunderstandings.
- [X] Double checked `~>help <command name>` (if this is command related) for potential misunderstandings.

**Describe the bug**
When using gelbooru without the questionable or explicit rating, the command fails with "There was an error while looking for this tag."

**To Reproduce**
Run ~>gelbooru white_hair safe
(Can be any tag)

**Expected behavior**
Returns an image from Gelbooru.

**Additional context**
Gelbooru recently updated their ratings to have 4 values (general, sensitive, questionable, explicit) instead of 3.
Since then, the new tags, and the old removed one (safe) cause the command to fail.

**Comment by Kodehawa** [comment]
Hello, could you mirror this issue to https://github.com/Kodehawa/imageboard-api/

Thanks you.
