### ISSUE TITLE
Love don't work

### ISSUE THREAD

**Issue by Miala-python** [Mantaro/MantaroBot#704]
Hello, we can't test love enter two user:

Method 1: don't work
![Screenshot_2022-09-03-16-56-18-712_com.discord.png](https://user-images.githubusercontent.com/65893041/188276263-720a52fe-fb55-4bde-bbb0-e08ff6321b72.png)

Method 2: no place for the second user
![Screenshot_2022-09-03-16-57-04-507_com.discord.png](https://user-images.githubusercontent.com/65893041/188276293-251fd98a-ff42-4ce8-bca1-9c7ed7506f55.png)

Solution (I think) : put a second optional argument for second user.

Thanks

**Comment by Kodehawa** [comment]
oops
