### ISSUE TITLE
items in inventory supposed to do something?

### ISSUE THREAD

**Issue by vluu2** [Mantaro/MantaroBot#77]
Idk where to ask this question so I hope someone could direct me to proper place to ask or give me an answer.

What do we do with the items in our inventory for the currency commands? Do any of them do anything? 
Besides the crate box / key & brom's pickaxe. What do the other items do? 

I don't see a ~>use [item name] ..

**Comment by Kodehawa** [comment]
Most of them are just for display *for now*
More uses are planned for the foreseeable future :)
