### ISSUE TITLE
[Suggestion/Feature Request]: Add birthday announcement timezone override

### ISSUE THREAD

**Issue by HiLordReilo** [Mantaro/MantaroBot#791]
### Before submitting, I have

- [X] Double-checked existing Issues/Pull Requests for a similar feature (including closed ones).
- [X] Double-checked the feature does not exist already in either the same or differing way.
- [X] Double-checked the feature has not been rejected before.

### Describe what you would like us to add

I feel like this should be customizable as well
![image](https://github.com/Mantaro/MantaroBot/assets/68978107/27dda540-b7c2-4dfc-9f6a-7654f7453a0f)

Maybe make use of `/profile timezone` command for determining the midnight for announcement per user?

**Comment by MrLar** [comment]
This is impossible for us to maintain as it would essentially require us to check at the top of every hour if a user has their birthday, as realistically speaking every timezone has at least one user in it. It would also require us to handle edge cases, such as timezones that aren't full hours offset (yes,  those exist). All of that and the sheer number of users and servers we are dealing with here leads to the fact that supporting timezones does not scale well and would lead to significant slow down of either the entire bot or the birthday system.

**Comment by HiLordReilo** [comment]
I see. Sorry, did not take the performance impact this may have into consideration
