### ISSUE TITLE
no shopper badge

### ISSUE THREAD

**Issue by BobJohns** [Mantaro/MantaroBot#83]
![image](https://user-images.githubusercontent.com/32987400/31854737-1300e3e6-b696-11e7-8080-2554f297050b.png)
it says here that to get the shopper badge you need 5000 of any given item at one time. 
![image](https://user-images.githubusercontent.com/32987400/31854751-33914b6e-b696-11e7-9bfb-b6df2d81a2be.png)
so why don't i have the badge???

**Comment by natanbc** [comment]
Use `~>inventory` to get the badge.

**Comment by BobJohns** [comment]
ok safe

**Comment by MrLar** [comment]
@Kodehawa @natanbc You should also grant the badge when opening the profile tbh less confusion
