### ISSUE TITLE
My badge is not registering :(

### ISSUE THREAD

**Issue by Emperor-of-Time** [Mantaro/MantaroBot#88]
For whatever reason, when achieving the Shopper badge it will not register on my profile and will not show up when I use ~>badges. I bought 5000 shoes and have had them for 2 days but it will not appear, I have 3 badges currently, Lucky, Claimer, and Gamer. Maybe there is a max on how many badges I can have but if there is I was not aware of it. When getting my other badges they appeared in the hour so I'm not sure whats going on with it.

PS. I have never used this website before so I'm not sure if this is even the right place for this 😆 

Edit: Someone told me to do ~>inventory and then do ~>badges and it worked, for whatever reason it will not appear anymore but thanks dude

**Comment by ILuvSpaghetti** [comment]
Do `~>inventory ` & then check your badges.
