### ISSUE TITLE
Badges problem

### ISSUE THREAD

**Issue by ToadMaster** [Mantaro/MantaroBot#92]
Hey, there is not à long time ago, i've seen this thing, ans i don't think is it's really normal, m'y friend have sais me that on her computer it's thé samedi situation, she has 6 badges, but only 5 are on her profile. I hope you'll can help. There are thé screenshots on my phone
![screenshot_2017-12-14-20-47-34](https://user-images.githubusercontent.com/34553642/34011899-0b9141b8-e112-11e7-8174-6737637715a7.png)
![screenshot_2017-12-14-20-47-24](https://user-images.githubusercontent.com/34553642/34011900-0c1d6094-e112-11e7-801c-a2b2ddc24833.png)

**Comment by ToadMaster** [comment]
I wrote "thé samedi situation" but i wanted to say "the same situation"

**Comment by MrLar** [comment]
![](https://shuvi.ratelimited.today/46df24.jpg)

**Comment by ToadMaster** [comment]
Thank you for tout help, i've never seen it before
