### ISSUE TITLE
Birthday announcements are not working

### ISSUE THREAD

**Issue by KarnaughAtlas** [Mantaro/MantaroBot#95]
Hi there - I believe I've set this up correctly, but birthday announcements are not working. Here are the commands I issued and Mantaro's responses:

KarnaughAtlas - Yesterday at 9:52 AM
~>opts birthday enable announcements BirthdayMonarch
MantaroBOT - Yesterday at 9:52 AM
:mega: Birthday logging enabled on this server with parameters -> Channel: #announcements (361357225379495946) and role: BirthdayMonarch (393082903820632082)

->birthday 21/12/2017
MantaroBOT - Yesterday at 10:25 AM
:white_check_mark: Added birthdate.
KarnaughAtlas - Yesterday at 10:26 AM
->birthday month
MantaroBOT - Yesterday at 10:26 AM
:heavy_multiplication_x: There are no birthdays for this month here :(

I ran those commands yesterday and was expecting to see an announcement about my birthday, and to have the birthday role assigned to me, but neither happened.

Let me know if you need any further information from me!

**Comment by MrLar** [comment]
Birthdays are cached every 23 hours you will not show up until you are in the cache. In other words you will show up tomorrow.

**Comment by KarnaughAtlas** [comment]
Oh - you're right! I just ran ->birthday month and they are now showing up correctly. Thank you for your disturbingly fast reply! Closing this issue.
