### ISSUE TITLE
I can't find how to accept a mariage, am I too dumb ?

### ISSUE THREAD

**Issue by twarlik** [Mantaro/MantaroBot#97]
I've tryed what you showed on another post (#35) 
(like this : ~>marry @mention yes)
but I've I just can't do it, may you guys help pls ?

**Comment by ILuvSpaghetti** [comment]
You do `~>marry @user` & the user types Yes or No or accept or deny the proposal.

**Comment by twarlik** [comment]
then i must be really dumb because i just dont suceed doing it

**Comment by twarlik** [comment]
do you have a discord ? so you guys could help me irl ?

**Comment by ILuvSpaghetti** [comment]
It has a timeout, the user you tag needs to reply to the proposal before a time runs out or you've to execute the command again.

**Comment by twarlik** [comment]
do I have to type 
->marry Yes
or simply 
->Yes

**Comment by ILuvSpaghetti** [comment]
Do `~>invite` & join the support guild.

**Comment by ILuvSpaghetti** [comment]
Type yes or no without the prefix lol.

**Comment by twarlik** [comment]
it worked, damn man, all the time I though we needed to add the prefix, well, hope this will help future people like me, happy year to you

**Comment by Kodehawa** [comment]
Next update will accept prefixed answers on marry because too many people seem to think it's with the prefix...

**Comment by moonstarcat524** [comment]
You just say Yes that’s all.

**Comment by Kodehawa** [comment]
Someone already replied and this is closed though.
