### ISSUE TITLE
Request: ~>eat and ~>drink (Item Consumption)

### ISSUE THREAD

**Issue by tobyink** [Mantaro/MantaroBot#99]
It would be good if you could eat and drink chocolates, cookies, milk, and alcohol.

Perhaps if you have recently eaten, you could be more likely to succeed when mining (because you have more energy). If you've recently consumed alcohol, you might be _less_ likely to succeed, though milk could neutralise alcohol.

**Comment by MrLar** [comment]
Are more in-depth item system is planned and our Github is more meant for actual issues like bugs for feature please refer to our [Support Guid](https://discord.gg/6upDzdh).

**Comment by moonstarcat524** [comment]
The ~eat and ~drink command can be made using the custom commands command ~custom new eat You are eating.
~custom new drink You are drinking.

**Comment by MrLar** [comment]
That is not what he meant. He means a more in-depth item system where you can consume items to gain benefits not custom commands

**Comment by MrLar** [comment]
also ~ is not a global prefix.

**Comment by MrLar** [comment]
While eating an drinking is not part of it. Items have been giving some more uses in 5.0 and we will continue to add more uses in the future.
